import test from 'node:test';import assert from 'node:assert/strict';
import {findTaskSignature,readFindProgress,readCircuitProgress} from '../src/explorationProgress.mjs';
const task={key:'known',kind:'section',plane:'coronal',position:50,rotation:{x:0,y:0,z:0},hemisphere:'both',medial:false,overlay:'none',highlight:{ids:[1]}};
const find=()=>({taskKey:'known',signature:findTaskSignature(task),start:{plane:'horizontal',position:52},state:{stage:'search',answerChecked:false,plane:'horizontal',position:53,rotation:{x:3,y:7,z:0},zoom:1.4,pan:{x:5,y:8},guess:{x:42,y:55},reading:{scroll:30,openDetails:[0]}}});
const reg={circuits:{loop:{paths:[{key:'direct',nodes:['a','b','a']},{key:'indirect',nodes:['a','c','b']}]},other:{paths:[{key:'same',nodes:['a','z']}]}},freeKeys:['region:known'],basalCount:4,papezCount:5,visualCount:5};
const circuit=()=>({selected:'loop',inspector:'circuits',positions:{loop:{pathKey:'direct',nodeIndex:2,nodeKey:'a'},other:{pathKey:'same',nodeIndex:1,nodeKey:'z'}},readings:{'loop|direct|2|a':{scroll:140,openDetails:[0,2]}},view:{rotation:{x:0,y:8,z:0},zoom:1.2,pan:{x:0,y:0},hemisphere:'left',mobilePane:'guide',freeSelections:['region:known'],freeFocused:'region:known',ghost:true,cerebellum:false,vessels:false,nerves:false,ponsMedulla:true,sectionsOpen:false,basalStep:1,papezStep:2,visualIndex:null},sectionOrigin:null});
test('finding resumes guess/pose and an unanswered or hinted state without promotion',()=>{for(const stage of ['search','hint']){const s=find();s.state.stage=stage;const got=readFindProgress(s,[task]);assert.equal(got.state.stage,stage);assert.equal(got.state.answerChecked,false);assert.deepEqual(got.state.guess,{x:42,y:55});assert.equal(got.state.position,53);}});
test('revealed answer requires matching explicit reveal flag and current task signature',()=>{const s=find();s.state.stage='answer';assert.equal(readFindProgress(s,[task]),null);s.state.answerChecked=true;assert.equal(readFindProgress(s,[task]).state.stage,'answer');assert.equal(readFindProgress(s,[{...task,highlight:{ids:[2]}}]),null);});
test('deleted task, invalid positions and marker coordinates never restore',()=>{for(const mutate of [s=>s.taskKey='deleted',s=>s.start.position=101,s=>s.state.rotation.x=Infinity,s=>s.state.guess.y=-1,s=>s.state.reading.openDetails=[201]]){const s=find();mutate(s);assert.equal(readFindProgress(s,[task]),null);}});
test('repeated circuit nodes retain their exact occurrence; separate circuits retain separate positions',()=>{const got=readCircuitProgress(circuit(),reg);assert.equal(got.positions.loop.nodeIndex,2);assert.equal(got.positions.loop.nodeKey,'a');assert.equal(got.positions.other.nodeKey,'z');});
test('deleted node/path/circuit and index-node disagreement are rejected',()=>{for(const mutate of [s=>s.positions.loop.nodeKey='deleted',s=>s.positions.loop.pathKey='old-path',s=>s.selected='removed',s=>s.positions.loop.nodeIndex=1]){const s=circuit();mutate(s);assert.equal(readCircuitProgress(s,reg),null);}});
test('reading state belongs to exact circuit/path/node occurrence and cannot mix',()=>{const s=circuit();s.readings['loop|indirect|1|c']={scroll:90,openDetails:[]};assert.ok(readCircuitProgress(s,reg));s.readings['loop|indirect|1|a']={scroll:90,openDetails:[0]};assert.equal(readCircuitProgress(s,reg),null);});
test('old free-selection IDs and out-of-range steppers cannot reach renderer',()=>{for(const mutate of [s=>s.view.freeSelections=['region:deleted'],s=>s.view.papezStep=99,s=>s.view.visualIndex=9,s=>s.view.zoom=0]){const s=circuit();mutate(s);assert.equal(readCircuitProgress(s,reg),null);}});
test('section return cannot refer to a different selected circuit',()=>{const s=circuit();s.sectionOrigin='other';assert.equal(readCircuitProgress(s,reg),null);s.sectionOrigin='loop';assert.ok(readCircuitProgress(s,reg));});

test('restored zoom obeys separate slice and model renderer bounds',()=>{const model={...task,kind:'surface'};for(const value of [.7,2.4]){const s=find();s.signature=findTaskSignature(model);s.start=null;s.state.plane=task.plane;s.state.zoom=value;assert.ok(readFindProgress(s,[model]));}for(const value of [.69,2.401,5]){const s=find();s.signature=findTaskSignature(model);s.start=null;s.state.plane=task.plane;s.state.zoom=value;assert.equal(readFindProgress(s,[model]),null);}const s=find();s.state.zoom=.7;assert.equal(readFindProgress(s,[task]),null);s.state.zoom=.75;assert.ok(readFindProgress(s,[task]));s.state.zoom=5;assert.ok(readFindProgress(s,[task]));});
import {CIRCUIT_TEACHING} from '../src/circuitTeaching.mjs';
test('all authored circuit/path/node occurrences can roundtrip through the stable-ID reader',()=>{let occurrences=0;const registry={...reg,circuits:CIRCUIT_TEACHING};for(const [key,c] of Object.entries(CIRCUIT_TEACHING))for(const path of c.paths)for(let index=0;index<path.nodes.length;index++){const s={selected:key,inspector:'circuits',positions:{[key]:{pathKey:path.key,nodeIndex:index,nodeKey:path.nodes[index]}},readings:{[`${key}|${path.key}|${index}|${path.nodes[index]}`]:{scroll:23,openDetails:[]}},view:null,sectionOrigin:null};const got=readCircuitProgress(JSON.parse(JSON.stringify(s)),registry);assert.ok(got,`${key}/${path.key}/${index}`);assert.deepEqual(got.positions,s.positions);occurrences++;}assert.ok(occurrences>30);});
test('a valid numeric index with a wrong authored node ID is rejected',()=>{const registry={...reg,circuits:CIRCUIT_TEACHING};for(const [key,c] of Object.entries(CIRCUIT_TEACHING)){const path=c.paths[0],other=path.nodes.find(node=>node!==path.nodes[0]);assert.ok(other);const s={selected:key,inspector:'circuits',positions:{[key]:{pathKey:path.key,nodeIndex:0,nodeKey:other}},readings:{},view:null,sectionOrigin:null};assert.equal(readCircuitProgress(s,registry),null)}});
