import test from 'node:test';import assert from 'node:assert/strict';
import {scheduleReadingRestore} from '../src/scheduleReadingRestore.mjs';
function frames(ignoreCancel=false){let id=0;const jobs=new Map();return {request(fn){jobs.set(++id,fn);return id},cancel(n){if(!ignoreCancel)jobs.delete(n)},tick(){const batch=[...jobs];for(const [n,fn] of batch){jobs.delete(n);fn()}},get size(){return jobs.size}};}
test('reading applies only after both frames',()=>{const f=frames();let applied=0;scheduleReadingRestore(f.request,f.cancel,()=>applied++);f.tick();assert.equal(applied,0);f.tick();assert.equal(applied,1);f.tick();assert.equal(applied,1)});
test('unmount before first frame cancels all pending restoration',()=>{const f=frames();let applied=0;const stop=scheduleReadingRestore(f.request,f.cancel,()=>applied++);stop();assert.equal(f.size,0);f.tick();f.tick();assert.equal(applied,0)});
test('switching node between frames cancels second frame',()=>{const f=frames();let oldAnswerOpened=false;const stop=scheduleReadingRestore(f.request,f.cancel,()=>oldAnswerOpened=true);f.tick();stop();assert.equal(f.size,0);f.tick();assert.equal(oldAnswerOpened,false)});
test('even a queued callback delivered after cancel cannot restore old node answers',()=>{const f=frames(true),applied=[];const stop=scheduleReadingRestore(f.request,f.cancel,()=>applied.push('old'));f.tick();stop();scheduleReadingRestore(f.request,f.cancel,()=>applied.push('new'));f.tick();f.tick();assert.deepEqual(applied,['new'])});
test('late first-frame callback after cleanup cannot schedule a second frame',()=>{const f=frames(true);let applied=0;const stop=scheduleReadingRestore(f.request,f.cancel,()=>applied++);stop();f.tick();assert.equal(f.size,0);f.tick();assert.equal(applied,0)});
test('cleanup after completion is idempotent',()=>{const f=frames();let applied=0;const stop=scheduleReadingRestore(f.request,f.cancel,()=>applied++);f.tick();f.tick();stop();stop();f.tick();assert.equal(applied,1)});
