import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import ts from 'typescript';
import {renderToStaticMarkup} from 'react-dom/server';
import {createElement} from 'react';

const source=await readFile(new URL('../app/SegmentationReferences.tsx',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS}}).outputText;
const exported={};
const nativeRequire=createRequire(import.meta.url);
const searchSource=await readFile(new URL('../src/japaneseSearch.ts',import.meta.url),'utf8');
const searchExports={};
vm.runInNewContext(ts.transpileModule(searchSource,{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:searchExports,require:nativeRequire});
vm.runInNewContext(compiled,{exports:exported,require:name=>name==='../src/japaneseSearch'?searchExports:name.endsWith('.css')?{}:nativeRequire(name)});
for(const english of [false,true])test(`browser references render source roles and safely opened reference links (${english?'en':'ja'})`,async()=>{
  const html=renderToStaticMarkup(createElement(exported.SegmentationReferences,{english}));
  const anchors=html.match(/<a [^>]+>/g)||[];
  assert.ok(anchors.length>0);
  for(const anchor of anchors){
    assert.match(anchor,/href="https:\/\//);
    assert.match(anchor,/target="_blank" rel="noreferrer"/);
  }
  assert.match(html,/10.1038\/s41586-025-09708-2/);
  assert.match(html,english?/other specimens/:/別標本/);
  assert.match(html,/10.3389\/fnana.2022.894606/);
  assert.match(html,english?/have not been adopted wholesale/:/そのまま採用していません/);
  assert.match(html,/10.1016\/j.neuroimage.2015.02.065/);
  assert.match(html,/data-brainstem-representation="partial-tissue-repair"/);
  assert.match(html,english?/not a completed segmentation/:/全脳幹の完成分節でも/);
  assert.match(html,/17876227/);assert.match(html,/NBK540988/);
  assert.match(html,/data-aqueduct-representation="current-teaching-block"/);
  assert.match(html,english?/current midbrain teaching block uses a partial lumen cast/:/現行の中脳横断ブロックも同じラベルから切り出した部分鋳型/);
  assert.match(html,english?/197- and 90-voxel/:/197点・90点/);
  assert.match(html,/s00276-024-03312-1/);
  assert.match(html,english?/missing specimen walls/:/標本で失われた壁/);
  assert.match(html,/s41597-019-0217-0/);
  assert.match(html,/3394010/);
  assert.match(html,/NBK553189/);
  assert.match(html,/NBK538491/);
  assert.match(html,/NBK10847/);
  assert.match(html,/PMC3543080/);
  assert.match(html,/PMC3424008/);
  assert.match(html,english?/partial crossing/:/部分交叉/);
  assert.match(html,english?/not adopted boundary data/:/採用境界データではありません/);
  assert.match(html,english?/expert review/:/専門家レビュー/);
  if(english)assert.doesNotMatch(html,/[ぁ-んァ-ヶ一-龠]/);
  const page=await readFile(new URL('../app/page.tsx',import.meta.url),'utf8');
  assert.match(page,/<SegmentationReferences english=\{englishEdition\}\/>/);
});
