import test from 'node:test';import assert from 'node:assert/strict';import{WINDOWS_QUIZ_PROGRESS_KEY as key,quizProgressToken as token,readWindowsQuizProgress as read,writeWindowsQuizProgress as write}from '../src/windowsQuizProgress.mjs';
const questions=[{id:'one',target:'a',category:'basal',prompt:'One',options:['a','b']},{id:'two',target:'b',category:'basal',prompt:'Two',options:['b','a']}],registry={revision:'r',contentRevision:'c',circuits:{}};
const record={version:1,revision:'r',contentRevision:'c',queue:questions.map(token),options:questions.map(q=>q.options),index:1,finished:false,openMissedNumber:null,answers:['b',null],title:null,origin:null,originKind:null,circuit:null,circuitView:null,circuitReturn:null};
const raw=JSON.stringify(record);
test('valid current set keeps exact order and selected answer',()=>assert.deepEqual(read(raw,questions,registry).value,record));
test('incomplete earlier answers and future answers rejected',()=>{for(const answers of [[null,null],['b','unknown']])assert.equal(read(JSON.stringify({...record,answers}),questions,registry).status,'invalid');});
test('old content and changed question cannot restore answers',()=>{assert.equal(read(raw,questions,{...registry,contentRevision:'different'}).status,'revision-mismatch');assert.equal(read(raw,[{...questions[0],prompt:'Changed'},questions[1]],registry).status,'unrestorable');});
test('finished requires all answers and last position',()=>{assert.equal(read(JSON.stringify({...record,finished:true}),questions,registry).status,'invalid');assert.equal(read(JSON.stringify({...record,finished:true,answers:['b','b']}),questions,registry).status,'valid');});
test('malformed and unknown-version records are not overwritten',()=>{for(const previous of ['broken',JSON.stringify({...record,version:99})]){let stored=previous;const storage={getItem:()=>stored,setItem:(_,v)=>stored=v};assert.equal(write(storage,previous,raw,questions,registry).status,'blocked');assert.equal(stored,previous);}});
test('concurrent change leaves newer raw intact',()=>{let stored='newer';const storage={getItem:()=>stored,setItem:(_,v)=>stored=v};assert.equal(write(storage,raw,raw,questions,registry).status,'conflict');assert.equal(stored,'newer');});
test('written record must be read back and storage refusal remains unavailable',()=>{let stored=null;const storage={getItem:()=>stored,setItem:(_,v)=>stored=v};assert.equal(write(storage,null,raw,questions,registry).status,'saved');assert.deepEqual(read(stored,questions,registry).value,record);assert.equal(write({getItem:()=>null,setItem:()=>{}},null,raw,questions,registry).status,'unavailable');});

test('origin kind must agree with an actual restorable origin',()=>{assert.equal(read(JSON.stringify({...record,originKind:'theme'}),questions,registry).status,'invalid');assert.equal(read(JSON.stringify({...record,originKind:'related'}),questions,registry).status,'invalid');});
test('option shuffle keeps identity but preserves exact visible order',()=>{assert.equal(token(questions[0]),token({...questions[0],options:[...questions[0].options].reverse()}));const saved={...record,options:record.options.map(options=>[...options].reverse())};assert.deepEqual(read(JSON.stringify(saved),questions,registry).value.options,saved.options);});

test('resume reading points only to a missed question in a completed run',()=>{const finished={...record,finished:true,answers:['b','b']};assert.equal(read(JSON.stringify({...finished,openMissedNumber:1}),questions,registry).value.openMissedNumber,1);assert.equal(read(JSON.stringify({...finished,openMissedNumber:2}),questions,registry).status,'invalid');assert.equal(read(JSON.stringify({...record,openMissedNumber:1}),questions,registry).status,'invalid');});
