import {useId,useRef,useState} from 'react';
import {normalizeJapaneseSearch} from '../src/japaneseSearch';
import './reference-search.css';

const sources = [
  {name:"UTHealth Neuroanatomy Online — Extraocular Muscles",url:"https://nba.uth.tmc.edu/neuroanatomy/L8/Lab08p17_index.html",ja:"III・IV・VIがそれぞれ支配する外眼筋を見分ける四択の参考。模式脳神経の形状や個々の筋を表示する資料ではありません。",en:"Reference for distinguishing the extraocular muscles supplied by III, IV and VI in review questions. It does not validate the schematic nerve shapes or display the individual muscles."},
  {name:"NIH MeSH — Olfactory Nerve",url:"https://www.ncbi.nlm.nih.gov/mesh/68009832",ja:"嗅神経（I）の線維と嗅球を区別する用語の参考。模式3Dは嗅球・嗅索を示し、細い神経根糸は含みません。",en:"Terminology reference distinguishing olfactory nerve (I) fibres from the olfactory bulb. The schematic shows the bulb and tract, not fine nerve filaments."},
  {name:"NIH MeSH — Optic Nerve",url:"https://www.ncbi.nlm.nih.gov/mesh/68009900",ja:"視神経（II）と視交叉後の視索を分けて説明するための用語の参考。",en:"Terminology reference for distinguishing the optic nerve (II) from the tract beyond the chiasm."},
  {name:"NIH MeSH — Optic Tract",url:"https://www.ncbi.nlm.nih.gov/mesh/68065866",ja:"視索を視交叉から外側膝状体などへ向かう経路として扱うための用語の参考。",en:"Terminology reference for the optic tract running from the chiasm toward the lateral geniculate bodies and other targets."},
  {name:"UTHealth Neuroanatomy Online — Medial structures",url:"https://nba.uth.tmc.edu/neuroanatomy/L1/Lab01p22_index.html",ja:"透明中隔と脳梁など、内側面の位置関係を学ぶための参考。解説を照合し、画像は転載していません。",en:"Reference for learning medial relationships, including the septum pellucidum and corpus callosum. Used to check explanations; images are not reproduced."},
  {name:"UTHealth Neuroanatomy Online — Limbic system: sectional review",url:"https://nba.uth.tmc.edu/neuroanatomy/L11/Lab11p09_index.html",ja:"前交連・脳弓・乳頭体を連続断面で見分ける説明の参考。別標本の境界を転写する用途ではありません。",en:"Reference for distinguishing the anterior commissure, fornix and mammillary bodies across sections. Not used to transfer boundaries from another specimen."},
  {name:"千田隆夫・小村一也 — プラクティカル解剖実習 脳（2012）, pp.71–77",nameEn:"Practical Anatomy Dissection: Brain (Japanese textbook, 2012), pp.71–77",url:"https://ndlsearch.ndl.go.jp/books/R100000002-I024104001",ja:"側脳室を段階的に開き、下角と海馬を観察する剖出の参考。ユーザー提供の書籍ビューアーで図を確認。仮想標本の切除範囲は本教材で設計し、書籍画像は転載していません。",en:"Dissection reference for opening the lateral ventricle and viewing the inferior horn and hippocampus. Figures were consulted in the user-provided book viewer. Virtual cuts are designed for this app; no book images are reproduced."},
  {name:"Texas Tech — Neuroanatomy 2 lab manual",url:"https://anatomy.ttuhscep.edu/schemes/neuro2.html",ja:"正中・水平・冠状の切断面で内部構造を観察する実習方針の参考。ブロックの具体的な座標は本教材で設定し、文献の標本や手技を正確に再現したものではありません。",en:"Reference for learning internal structures on midline, horizontal and coronal sections. Block coordinates are defined for this teaching app; they do not reproduce the source specimens or procedures exactly."},
  {name:"Allen Human Brain Reference Atlas — coronal plate 67",url:"https://atlas.brain-map.org/atlas?atlas=138322605&plate=112363222&structure=266441621",ja:"別標本の冠状断67で注釈図とNissl画像を確認。タペタム・矢状層内外層・視放線の位置を比較する資料です。視放線の位置注釈を独立した輪郭マスクとは扱わず、BigBrainへ転写していません。",en:"Annotated and Nissl views of coronal plate 67 reviewed in a different specimen, for tapetum, sagittal-stratum layers and optic-radiation position. A positional annotation is not treated as an independent tract mask or transferred to BigBrain."},
  {name:"Gülsuna et al. (2024) — Revisiting the sagittal stratum",url:"https://pubmed.ncbi.nlm.nih.gov/38820606/",ja:"抄録を確認。矢状層内層にも交錯する投射線維が含まれるため、内層全体を視放線とする根拠にはしません。本文・図は未確認です。",en:"Abstract reviewed: the internal sagittal-stratum layer also contains intertwined projection fibers, so it is not equated wholesale with optic radiation. Full text and figures have not been reviewed."},
  {name:"Amunts et al. (2013) — BigBrain",url:"https://bigbrainproject.org/",ja:"原組織画像。脳室などの境界を連続断・直交断で照合。表示用画像は再標本化した派生物です。",en:"Source histology for contiguous and orthogonal boundary review, including the ventricles. Display images are resampled derivatives."},
  {name:"Xiao et al. (2019) — BigBrain registration",url:"https://doi.org/10.1038/s41597-019-0217-0",ja:"手動皮質下核ラベルと位置合わせ。赤核・淡蒼球などの区画と、登録300 µm画像による照合に使用。",en:"Manual subcortical labels and registration, including red nucleus and pallidal subdivisions; registered 300 µm images used for review."},
  {name:"Manera et al. (2020) — CerebrA",url:"https://doi.org/10.1038/s41597-020-0557-9",ja:"アトラス対応と初期ラベルの由来。同一標本の手動分節とは区別しています。",en:"Atlas mappings and initial labels; distinct from manual segmentation of the same specimen."},
  {name:"Paquola et al. (2021) — BigBrainWarp",url:"https://doi.org/10.7554/eLife.70119",ja:"脳表モデルの元となる配布表面データ。アプリ独自の形状加工や溝ガイドは原論文の確定境界ではありません。",en:"Distributed surface data underlying the surface model. App-specific shape modifications and sulcal guides are not validated boundaries from this paper."},
  {name:"Schiffer et al. — BigBrain lateral geniculate body six-layer dataset",url:"https://doi.org/10.25493/33Z0-BX",ja:"同一BigBrain標本の専門家参照と深層学習支援による左右6層分節です。公式フル変換で0.5 mm格子へ最近傍再標本化し、層の和集合だけを使用しています。CC BY-NC-SA 4.0。プロジェクトでの採用はAI照合で、専門家レビュー済みとは扱いません。",en:"Expert-reference and deep-learning-assisted six-layer segmentations of both lateral geniculate bodies in the same BigBrain specimen. The union of layers was resampled by nearest neighbour onto the 0.5 mm grid through the official full transform. CC BY-NC-SA 4.0. Project adoption was AI-assisted and is not treated as expert review."},
];
const readings = [
  {name:"UTHealth Neuroanatomy Online — Cerebellum",url:"https://nba.uth.tmc.edu/neuroanatomy/l5/Lab05p21_index.html",ja:"運動の調整・学習だけでなく、運動計画への関与を含めた小脳の復習解説に使用。",en:"Used to explain cerebellar contributions to motor planning as well as coordination and learning in the review quiz."},
  {name:"Texas Tech — Cranial nerves: facial nerve",url:"https://anatomy.ttuhscep.edu/modules/CN_module/cnVII.html",ja:"顔面神経の機能問題で、涙腺・顎下腺・舌下腺への副交感支配を明確にするために参照。画像は転載していません。",en:"Used to specify facial parasympathetic supply to lacrimal, submandibular and sublingual glands. No images are reproduced."},
  {name:"UAMS — Nerves of the head and neck",url:"https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/nerve-tables/nerves-of-the-head-and-neck/",ja:"耳下腺の副交感支配と、舌筋のうち口蓋舌筋の支配が異なることを復習解説と照合。神経モデルの末梢分枝は追加していません。",en:"Used to check parotid parasympathetic supply and the different innervation of palatoglossus. Peripheral branches have not been added to the nerve models."},
  {name:"UTHealth Neuroanatomy Online — Head and body of the caudate nucleus",url:"https://nba.uth.tmc.edu/neuroanatomy/L10/Lab10p08_index.html",ja:"尾状核の頭部から体部への弯曲を断面で追う観察案内の参考。",en:"Reference for following the caudate head and curved body across sections."},
  {name:"UTHealth Neuroanatomy Online — Diencephalon/midbrain junction",url:"https://nba.uth.tmc.edu/neuroanatomy/L6/Lab06p11_index.html",ja:"赤核と周囲構造の位置関係を読む観察案内の参考。線維束の追加分節には使用していません。",en:"Reference for observing the red nucleus and its neighbours; not used to add tract segmentation."},
  {name:"UTHealth Neuroanatomy Online — External capsule and claustrum",url:"https://nba.uth.tmc.edu/neuroanatomy/L10/Lab10p14_index.html",ja:"被殻から島皮質までの層の並びを説明する参考。前障・外包・最外包の独立分節は追加していません。",en:"Reference for the layers between putamen and insula. Separate claustrum, external-capsule and extreme-capsule labels have not been added."},
  {name:"UTHealth Neuroanatomy Online — Cerebellum and brainstem",url:"https://nba.uth.tmc.edu/neuroanatomy/l5/Lab05p22_index.html",ja:"小脳虫部・半球と脳幹の位置関係を読む観察案内の参考。",en:"Reference for observing the vermis, cerebellar hemispheres and their relationship to the brainstem."},
  {name:"Schiffer et al. — BigBrain hOc1 / V1 cytoarchitectonic map",url:"https://doi.org/10.25493/DGEZ-Q93",ja:"同一標本の左右V1配布マップを粗い解像度で取得し、6原断面と位置を照合。視放線の皮質側の目印として調査中で、アプリの分節には未採用です。深層学習支援・補間・平滑化を含みます。CC BY-NC-SA 4.0。",en:"Coarse bilateral V1 maps from the same specimen were retrieved and compared with six source sections as cortical endpoint landmarks. Not adopted into the app segmentation. Includes deep-learning assistance, interpolation and smoothing. CC BY-NC-SA 4.0."},
  {name:"Rizzi et al. (2021 preprint) — Dorsal loop of the optic radiation",url:"https://www.researchsquare.com/article/rs-589114/v1",ja:"査読前著者版の方法・剖出結果・図2を確認。背側走行と鳥距溝、タペタムとの関係を比較する資料です。別標本の厚みやアトラスVOIは転写していません。2022年出版版の全文を確認したものではありません。",en:"Methods, dissection results and Figure 2 reviewed in the unreviewed preprint, for dorsal course and calcarine/tapetal relationships. Other-specimen thickness and atlas VOIs are not transferred. This is not a full-text review of the 2022 published version."},
  {name:"Li et al. (2026) — Medial-to-lateral fiber dissection",url:"https://doi.org/10.1007/s00701-026-06829-z",ja:"脳弓の本文と剖出図2Aを確認。前交連後方の下行と乳頭視床路の区別を照合に使用。別標本の形状は転写していません。",en:"Fornix text and dissection Figure 2A reviewed for the postcommissural descent and distinction from the mammillothalamic tract. Other-specimen geometry is not transferred."},
  {name:"UTHealth Neuroanatomy Online — Hypothalamic sections",url:"https://nba.uth.tmc.edu/neuroanatomy/L11/Lab11p17_index.html",ja:"本文と図1のB・C層で交連後脳弓の強調表示を確認。視床下部内の概略位置を照合し、染色の明暗をBigBrainへ流用していません。",en:"Text and highlighted postcommissural fornix in Figure 1 layers B and C reviewed for approximate hypothalamic position. Staining intensity is not transferred to BigBrain."},
  {name:"Di Carlo et al. (2019) — Microsurgical anatomy of the sagittal stratum",url:"https://pubmed.ncbi.nlm.nih.gov/31363919/",ja:"抄録を参照。矢状層には複数の線維束が重なるため、脳室外側の白質全域を視放線とすることは避けています。本文・図の照合は未実施です。",en:"Abstract consulted: several fiber bundles overlap in the sagittal stratum, so periventricular white matter is not labeled wholesale as optic radiation. Full text and figures have not been reviewed."},
  {name:"Nooij et al. (2015) — Optic radiations: dissection and tractography",url:"https://doi.org/10.3389/fnana.2015.00096",ja:"本文・剖出図3・模式断面図7を照合。側脳室下角の屋根・外側壁から後方を追う位置の目印として使用し、別標本の寸法や安全域をBigBrainのラベルへ転写していません。",en:"Text and dissection Figure 3 and schematic Figure 7 consulted for ventricular landmarks. Other-specimen dimensions and surgical safety zones are not used as BigBrain labels."},
  {name:"EADC–ADNI HarP — Hippocampal Segmentation User Manual, §3.4.4",url:"https://www.hippocampal-protocol.net/SOPs/LINK_PAGE/FINAL_RELEASE/02_Appendix-II_HarP-UserManual.pdf",ja:"海馬灰白質への付着と走行の変化を使う海馬采・脳弓の区分規約。本文と図6・7を確認し、原画像上の候補同定に使用。MRIの信号や他標本の輪郭は転写していません。",en:"Fimbria–fornix conventions based on attachment to hippocampal grey matter and change of course. The text and Figures 6–7 informed source-image candidate identification; MRI signal rules and other-specimen contours were not transferred."},
  {name:"González-Arnay et al. (2024) — Human hippocampal histological parcellation",url:"https://doi.org/10.1007/s00429-023-02725-9",ja:"図1の後方折り返しと図5の海馬采前端・海馬頭の組織像を比較。白板、海馬采、海馬頭の位置関係を読むための資料で、本標本の境界を確定するものではありません。",en:"Figure 1 and Figure 5 provide comparative landmarks for the posterior fimbrial turn, anterior fimbrial attachment, alveus and hippocampal head; they do not establish boundaries in this specimen."},
  {name:"AJNR (2004) — MR imaging of the temporal stem",url:"https://pubmed.ncbi.nlm.nih.gov/15140705/",ja:"線維解剖とMRIを対応させた視放線の位置関係。LGNから下角の屋根・外側へ向かう範囲と周辺束の区別に使用し、個体のMeyer loopの長さを固定しません。",en:"Dissection–MRI relationships of the optic radiation, including its course from the LGN toward the temporal-horn roof and lateral wall. No fixed individual Meyer-loop length is inferred."},
  {name:"MGH CMA — Subcortical Brain Structure Segmentation Manual",url:"https://cma.mgh.harvard.edu/wp-content/uploads/2023/04/HOA-Subcortical-Brain-Structure-Segmentation-Manual.pdf",ja:"PDF68ページの視交叉の収載規約を調査。MRIの区切りを参考にするもので、閾値や未標識領域の穴埋めをBigBrainへ適用していません。",en:"Investigated the optic-chiasm extent convention on PDF page 68. MRI landmarks are comparative guidance; thresholding and filling unlabeled tissue have not been applied to BigBrain."},
  {name:"Alkemade et al. (2022) — Manual delineation approaches for direct imaging of the subcortex",url:"https://doi.org/10.1007/s00429-021-02400-x",ja:"脳弓の冠状断追跡、透明中隔との分離、前交連を使う収載範囲の比較。MRI信号条件や別標本の境界は転写していません。",en:"Comparison for coronal fornix tracing, septal separation and anterior-commissure landmarks. MRI signal criteria and other-specimen boundaries have not been transferred."},
  {name:"Amaral et al. (2018) — Manual segmentation of the fornix, fimbria, and alveus",url:"https://doi.org/10.1016/j.neuroimage.2016.10.027",ja:"脳弓・海馬采・海馬白板を区別するMRI分節研究。概要と著者配布のラベル定義を確認し、実maskのBigBrain照合は未実施です。",en:"MRI segmentation research separating fornix, fimbria and alveus. The abstract and author-released label definitions were checked; the masks have not been aligned with BigBrain."},
  {name:"EPTN/INCA — Fornix contouring instructions",url:"https://cancerdata.org/tutorial/eptn-neuro-atlas-video-fornix/",ja:"前交連・脳室間孔・乳頭体上縁を用いる追跡規約の比較資料。本文を確認し、動画全編の確認や本標本への適用検証は未実施です。",en:"Comparison of tracing landmarks at the anterior commissure, interventricular foramina and superior mammillary border. Text was reviewed; the full video and application to this specimen have not been validated."},
  {name:"EPTN/INCA — Optic tract contouring instructions",url:"https://cancerdata.org/tutorial/eptn-neuro-atlas-video-optic-tract/",ja:"視交叉後外側から左右別に追い、識別不能な区間で止めるMRI手順の比較。固定長や模式線で本標本の束を補完する根拠ではありません。",en:"Comparison with MRI instructions to trace each tract from the posterolateral chiasm and stop where it cannot be distinguished. Not evidence for completing specimen tracts using fixed lengths or schematic lines."},
  {name:"Maldonado et al. (2021) — Composition and organization of the sagittal stratum",url:"https://pubmed.ncbi.nlm.nih.gov/33418529/",ja:"線維解剖研究の抄録を確認。矢状層に複数束が含まれるため、白質帯全体を視放線と同一視しない判断の参考です。",en:"The fiber-dissection study abstract was reviewed. Multiple bundles contribute to the sagittal stratum; a whole white-matter band should not be equated with the optic radiation."},
  {name:"Microsurgical anatomy of the sagittal stratum",url:"https://pubmed.ncbi.nlm.nih.gov/31363919/",ja:"視放線を周囲の白質束から区別するための矢状層の線維解剖比較。別標本の境界は転写していません。",en:"Fiber-anatomy comparison of the sagittal stratum used to distinguish the optic radiation from surrounding white-matter bundles. Boundaries from another specimen were not transferred."},
  {name:"Akeret et al. (2022) — Multimodal anatomy of the human forniceal commissure",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9314404/",ja:"線維解剖と組織像による脳弓体部・脚・正中膜の位置関係を比較しました。別標本の境界は転写せず、臨床用途や微細交連の量を教材へ追加していません。",en:"Consulted for fiber-dissection and histological relationships among the fornix body, crura and midline membrane. Boundaries from other specimens were not transferred, and no new clinical use or quantitative claim about the fine commissure was added to the material."},
  {name:"Naidich et al. (1986) — Anterior commissure: anatomic-MR correlation",url:"https://pubmed.ncbi.nlm.nih.gov/3941867/",ja:"抄録を参照。前交連の正中部と左右へ曲がる走行の比較資料です。BigBrainで見える帯の同定を検討するために使用し、別標本の境界は転写していません。",en:"Abstract consulted for the midline anterior commissure and its curving bilateral course. Used to investigate the band visible in BigBrain; boundaries from another specimen were not transferred."},
  {name:"Barany et al. (2020; online 2019) — Neural and vascular architecture of the septum pellucidum",url:"https://pubmed.ncbi.nlm.nih.gov/31374555/",ja:"抄録を参照。透明中隔とその下方の中隔領域、脳弓の位置関係を比較。薄い膜の範囲と周辺組織を区別する資料で、個々の分節境界の出典ではありません。",en:"Abstract consulted for relationships between the septum pellucidum, the underlying septal region and the fornix. Used to distinguish the thin membrane from adjacent tissue, not as a source of individual segmentation boundaries."},
  {name:"Barany et al. (2024) — Topographical anatomy of the septum verum",url:"https://doi.org/10.1038/s41598-024-68464-x",ja:"線維解剖・組織学による中隔領域の位置関係を参照。透明中隔の下方付着部や脳弓との移行を、単純な膜や一本の線維として扱わないための比較資料です。",en:"Fiber-dissection and histological context for septal relationships. Used to avoid treating the inferior septal attachment and transition to the fornix as a simple membrane or single tract."},
  {name:"UAMS — Visceral Structures of the Head and Neck",url:"https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/viscera-tables/visceral-structures-of-the-head-and-neck/",ja:"V・IX・X・XIの概略出現部と近位走行の比較資料。模式モデルの配置検討に使用し、別標本の境界や座標を分節へ転写していません。",en:"Comparison for approximate attachment and proximal course of cranial nerves V, IX, X and XI. Used in schematic placement review; boundaries and coordinates from another specimen are not transferred into segmentation."},
  {name:"StatPearls — Neuroanatomy, Cranial Nerve 11 (Accessory)",url:"https://www.ncbi.nlm.nih.gov/books/NBK507722/",ja:"副神経の脊髄由来線維の上行と、表示範囲・省略の整理に使用。模式形状を標本から追跡した神経根とは扱っていません。",en:"Used to distinguish the ascent of spinal accessory fibers and clarify display scope and omissions. Schematic geometry is not treated as a root traced from the specimen."},
  {name:"Sonne et al. — Neuroanatomy, Cranial Nerve (StatPearls)",url:"https://www.ncbi.nlm.nih.gov/books/NBK470353/",ja:"V・IX・X・XIの機能要約の照合に使用。模式形状を調整中の項目にも機能説明を残しています。標本の分節境界や神経根座標の出典ではありません。",en:"Used to cross-check function summaries for cranial nerves V, IX, X and XI. Function descriptions remain available while schematic geometry is being adjusted. This is not a source of specimen segmentation boundaries or root coordinates."},
  {name:"UTHealth Neuroanatomy Online — Pons and trigeminal nerve",url:"https://nba.uth.tmc.edu/neuroanatomy/l4/Lab04p21_index.html",ja:"三叉神経の橋前外側出現部と感覚根・運動根の一般的位置関係を照合。BigBrainでの根の同定や置換形状の採用根拠ではありません。",en:"Consulted for the general anterolateral pontine emergence and sensory/motor roots of the trigeminal nerve. This does not identify the roots in BigBrain or establish replacement geometry."},
  {name:"Casamitjana et al. (2025) — NextBrain",url:"https://doi.org/10.1038/s41586-025-09708-2",ja:"別標本の組織学的アトラスとラベル一覧を調査。脳弓・内包・視覚路の部位区分を比較する資料で、BigBrainの境界として転写・採用していません。",en:"Investigation of a histological atlas of other specimens and its label catalogue, for comparing subdivisions of the fornix, internal capsule and visual pathway. No boundaries have been transferred to or adopted for BigBrain."},
  {name:"Rushmore et al. (2022) — Anatomically curated subcortical segmentation",url:"https://doi.org/10.3389/fnana.2022.894606",ja:"脳室間孔・第三脳室・大脳横裂の区分を照合。MRIの運用上の区画は組織学的な自然境界と同一ではなく、この規約やラベルをそのまま採用していません。",en:"Context for the interventricular foramina, third ventricle and transverse cerebral fissure. Operational MRI regions are not identical to histological boundaries; this protocol and its labels have not been adopted wholesale."},
  {name:"Iglesias et al. (2015) — Bayesian segmentation of brainstem structures in MRI",url:"https://doi.org/10.1016/j.neuroimage.2015.02.065",ja:"Appendix Bの中脳分節規約を照合。MRIの補助線を組織学的な自然境界とは扱わず、本標本へ境界を転写していません。",en:"Appendix B consulted for the midbrain delineation protocol. MRI reference lines are not treated as natural histological boundaries or transferred to this specimen."},
  {name:"Longatti et al. (2007) — Endoscopic anatomy of the cerebral aqueduct",url:"https://pubmed.ncbi.nlm.nih.gov/17876227/",ja:"抄録を参照。中脳水道の内形と後交連などの位置関係の背景資料です。内視鏡所見を本標本の境界へ転写していません。",en:"Abstract consulted for aqueduct morphology and landmarks including the posterior commissure. Endoscopic findings were not transferred to this specimen's boundaries."},
  {name:"Rubino & Hogg — Cerebral Aqueduct (StatPearls, updated 2023)",url:"https://www.ncbi.nlm.nih.gov/books/NBK540988/",ja:"解剖解説を参照。第三・第四脳室との移行を区別する補助資料で、原画像や採用マスクの出典ではありません。",en:"Anatomical background for distinguishing transitions to the third and fourth ventricles; not a source image or adopted mask."},
  {name:"Campos da Silva et al. (2024) — Stereotactic anatomy of the third ventricle",url:"https://doi.org/10.1007/s00276-024-03312-1",ja:"第三脳室底と漏斗陥凹の位置関係を照合。標本で失われた壁を推測で再建したり、文献からボクセル境界を転写したりする根拠にはしていません。",en:"Context for the third-ventricle floor and infundibular recess. Not a basis for reconstructing missing specimen walls or transferring voxel boundaries."},
  {name:"Nagata, Rhoton & Barry (1988) — Microsurgical anatomy of the choroidal fissure",url:"https://pubmed.ncbi.nlm.nih.gov/3394010/",ja:"抄録を参照。側脳室下角・海馬采・脳槽の位置関係の照合。文献からボクセル境界を転写していません。",en:"Abstract consulted for relationships between the temporal horn, fimbria and cisterns. Voxel boundaries were not transferred from this paper."},
  {name:"Oculomotor fascicular anatomy — PubMed 23242853",url:"https://pubmed.ncbi.nlm.nih.gov/23242853/",ja:"赤核の外形と内部線維を区別する参考。局所の白い帯の線維名を確定する根拠ではありません。",en:"Context for distinguishing the red-nucleus outline from internal fibres; not identification of a specific pale band."},
  {name:"Sitek et al. (2019) — Subcortical auditory system",url:"https://doi.org/10.7554/eLife.48932",ja:"聴覚路核アトラスの比較調査。教材との空間対応が未解決で、分節へ未採用です。",en:"Comparison with an auditory-nucleus atlas. Spatial correspondence remains unresolved; not adopted into the teaching segmentation."},
  {name:"Jones et al. (2020) — BigBrain Workshop",url:"https://bigbrainproject.org/docs/4th-bb-workshop/20-06-26-BigBrainWorkshop-Jones.pdf",ja:"脳弓周辺の調査資料。脳弓の完成分節を取得・採用したものではありません。",en:"Background investigation around the fornix; not an acquired or adopted complete fornix segmentation."},
  {name:"UTHealth Neuroanatomy Online — Ventricles",url:"https://nba.uth.tmc.edu/neuroanatomy/L4/Lab04p01_index.html",ja:"側脳室・脳室間孔・第三脳室・中脳水道・第四脳室の順序と、視床周囲の位置関係を学ぶ参考。表示境界を確定する資料とは区別しています。",en:"Used for the order of the lateral ventricles, interventricular foramina, third ventricle, cerebral aqueduct and fourth ventricle, and for their relationships to the thalamus. This is anatomical context, not validation of displayed boundaries."},
  {name:"UTHealth Neuroanatomy Online — Internal Capsule",url:"https://nba.uth.tmc.edu/neuroanatomy/L10/Lab10p01_index.html",ja:"内包の前脚・膝・後脚を水平断で、周囲核との位置関係を冠状断で確認する観察案内に使用。",en:"Used to guide inspection of the anterior limb, genu and posterior limb in horizontal sections, and neighbouring nuclei in coronal sections."},
  {name:"UTHealth Neuroanatomy Online — Limbic system",url:"https://nba.uth.tmc.edu/neuroanatomy/L11/Lab11p06_index.html",ja:"Papez回路の構成と歴史的位置づけを回路解説に使用。概念上の結合を標本由来形状として扱っていません。",en:"Used for the components and historical context of the Papez circuit. Conceptual connections are not treated as specimen-derived geometry."},
  {name:"StatPearls — Neuroanatomy, Limbic System",url:"https://www.ncbi.nlm.nih.gov/books/NBK538491/",ja:"Papez回路を含む辺縁系の構成と機能の照合に使用。回路概念をBigBrainの分節境界へ転写していません。",en:"Used to cross-check limbic-system organization and function, including the Papez circuit. Circuit concepts were not transferred to BigBrain segmentation boundaries."},
  {name:"Gupta et al. — Neuroanatomy, Visual Pathway (StatPearls)",url:"https://www.ncbi.nlm.nih.gov/books/NBK553189/",ja:"網膜から一次視覚野までの主経路、視交叉での部分交叉、外側膝状体と視放線の解説に使用。模式線維を実標本の分節とは区別しています。",en:"Used for the main retina-to-V1 route, partial crossing at the chiasm, lateral geniculate relay and optic radiation. Schematic fibers remain distinct from specimen segmentation."},
  {name:"UTHealth Neuroscience Online — Visual Processing: Cortical Pathways",url:"https://nba.uth.tmc.edu/neuroscience/s2/chapter15.html",ja:"視野と網膜の左右、視索の両眼性入力、外側膝状体から視放線への中継を回路の確認問題と照合。分節や個別線維を追加したものではありません。",en:"Used for self-review of visual-field and retinal sides, input from both eyes to each optic tract, and the LGN-to-optic-radiation relay. No segmentation or individual fibre geometry was added."},
  {name:"UTHealth Neuroscience Online — Basal Ganglia (James Knierim)",url:"https://nba.uth.tmc.edu/neuroscience/s3/chapter04.html",ja:"黒質緻密部のドパミン投射と、網様部・淡蒼球内節の出力機能の区別を照合。表示ラベル内の細区分を新たに分節したものではありません。",en:"Used to distinguish dopaminergic projections from pars compacta and the output roles of pars reticulata and GPi. This does not add segmentation of these subdivisions."},
  {name:"Purves et al. — Circuits within the Basal Ganglia System",url:"https://www.ncbi.nlm.nih.gov/books/NBK10847/",ja:"直接路・間接路、脱抑制、視床下核から出力核への興奮性結合の解説に使用。概念図の線は分節・トラクト形状ではありません。",en:"Used for direct and indirect pathways, disinhibition and excitatory STN output to basal-ganglia output nuclei. Diagram lines are not segmented tract geometry."},
  {name:"Lanciego et al. (2012) — Functional neuroanatomy of the basal ganglia",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3543080/",ja:"基底核の並列回路とハイパー直接路を含む回路構成の照合に使用。",en:"Used to cross-check basal-ganglia circuit organization, including parallel and hyperdirect pathways."},
  {name:"The Superior Transvelar Approach to the Fourth Ventricle and Brainstem",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3424008/",ja:"第四脳室上部と上髄帆・上小脳脚の位置関係の比較資料。BigBrainの個々の分節境界は原画像で確認し、別標本の境界を転写していません。",en:"Comparison for the superior fourth ventricle and the relationships of the superior medullary velum and superior cerebellar peduncles. Individual BigBrain segmentation boundaries were checked against the source images; boundaries from another specimen were not transferred."},
];

export function SegmentationReferences({english}:{english:boolean}) {
  const [query,setQuery]=useState('');
  const searchId=useId();
  const input=useRef<HTMLInputElement>(null);
  const terms=query.normalize('NFKC').split(/\s+/).map(normalizeJapaneseSearch).filter(Boolean);
  const matches=(source:{name:string;nameEn?:string;url:string;ja:string;en:string})=>{
    const text=normalizeJapaneseSearch([source.name,source.nameEn,source.url,source.ja,source.en].join(' '));
    return terms.every(term=>text.includes(term));
  };
  const matchedSources=sources.filter(matches),matchedReadings=readings.filter(matches);
  const count=matchedSources.length+matchedReadings.length;
  return <section className="legalReferences" data-segmentation-references="true" data-no-localize>
    <h3>{english?"References and use in this app":"参考文献と本アプリでの用途"}</h3>
    <p>{english?"Primary sources and selected review references. Citation does not imply author endorsement or completed expert review. Resolution and review coverage differ between repairs.":"主要な出典と照合資料です。引用元による承認や専門家レビュー完了を意味しません。使用解像度・確認範囲は修正ごとに異なります。"}</p>
    <div className="referenceSearch"><label htmlFor={searchId}>{english?'Find a reference':'参考文献を探す'}</label><div><input ref={input} id={searchId} type="search" value={query} placeholder={english?'Structure, author or title':'構造名・著者名・資料名（例：脳弓、BigBrain）'} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{
      if(event.nativeEvent.isComposing||event.nativeEvent.keyCode===229)return;
      if(event.key==='Escape'&&query){event.preventDefault();event.stopPropagation();setQuery('')}
    }}/>{query&&<button type="button" onClick={()=>{setQuery('');input.current?.focus()}}>{english?'Clear':'クリア'}</button>}</div>
      <p role="status">{english?`${count} of ${sources.length+readings.length} references`:`${sources.length+readings.length}件中${count}件`}</p>
    </div>
    {count===0&&<p>{english?'No matching references. Try a shorter structure name, an author, or clear the search.':'一致する資料がありません。短い構造名や著者名で探すか、検索をクリアしてください。'}</p>}
    {matchedSources.length>0&&<><h4>{english?"Data, anatomy and teaching references":"データ・解剖・実習の参考資料"}</h4>
    {matchedSources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{english&&s.nameEn?s.nameEn:s.name}</a><br/>{english?s.en:s.ja}</p>)}</>}
    {matchedReadings.length>0&&<><h4>{english?"Context and investigation — not adopted boundary data":"照合・調査資料 — 採用境界データではありません"}</h4>
    {matchedReadings.map((s,index)=><p key={`${s.url}:${index}`}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a><br/>{english?s.en:s.ja}</p>)}</>}
    <details><summary>{english?"Representation notes":"表示モデルに関する補足"}</summary>
    <p data-cerebellar-representation="current-section-labels">{english?"The BigBrain cerebellum and brainstem shown in Sections are reconstructed from the current section labels. Local 197- and 90-voxel cerebellar folial repairs are included. Remaining gaps and isolated components have not been declared complete, and these section models are distinct from the MNI surface models.":"連続断面のBigBrain小脳・脳幹3Dは、断面と同じ現行ラベルから再構成しています。小脳葉の局所197点・90点修正を反映していますが、残る塗り落としや孤立成分の確認は未完了です。MNIの脳表モデルとは区別しています。"}</p>
    <p data-brainstem-representation="partial-tissue-repair">{english?"The BigBrain brainstem label used in Sections includes a partial image-guided repair toward the cerebral peduncles. Its upper extent remains unresolved. It is not a completed segmentation or the separate MNI surface scaffold.":"断面用のBigBrain脳幹ラベルは、大脳脚側の塗り落としを原画像に基づき一部補修しています。上方の範囲は未確定で、全脳幹の完成分節でも、別のMNI脳表モデルそのものでもありません。"}</p>
    <p data-aqueduct-representation="current-teaching-block">{english?"The partial cerebral aqueduct in Sections is an image-guided BigBrain label (ID41). The current midbrain teaching block uses a partial lumen cast from the same label; older schematic block assets are separate. Neither view establishes the full extent or transition boundaries of the aqueduct.":"断面画面の中脳水道候補（部分）はBigBrain画像誘導ラベルID41です。現行の中脳横断ブロックも同じラベルから切り出した部分鋳型を用い、旧模式ブロック部品とは区別します。どちらも水道の全長と移行境界を確定するものではありません。"}</p>
    </details>
  </section>;
}
