const sources = [
  {name:"Amunts et al. (2013) — BigBrain",url:"https://bigbrainproject.org/",ja:"原組織画像。脳室などの境界を連続断・直交断で照合。表示用画像は再標本化した派生物です。",en:"Source histology for contiguous and orthogonal boundary review, including the ventricles. Display images are resampled derivatives."},
  {name:"Xiao et al. (2019) — BigBrain registration",url:"https://doi.org/10.1038/s41597-019-0217-0",ja:"手動皮質下核ラベルと位置合わせ。赤核・淡蒼球などの区画と、登録300 µm画像による照合に使用。",en:"Manual subcortical labels and registration, including red nucleus and pallidal subdivisions; registered 300 µm images used for review."},
  {name:"Manera et al. (2020) — CerebrA",url:"https://doi.org/10.1038/s41597-020-0557-9",ja:"アトラス対応と初期ラベルの由来。同一標本の手動分節とは区別しています。",en:"Atlas mappings and initial labels; distinct from manual segmentation of the same specimen."},
  {name:"Paquola et al. (2021) — BigBrainWarp",url:"https://doi.org/10.7554/eLife.70119",ja:"脳表モデルの元となる配布表面データ。アプリ独自の形状加工や溝ガイドは原論文の確定境界ではありません。",en:"Distributed surface data underlying the surface model. App-specific shape modifications and sulcal guides are not validated boundaries from this paper."},
  {name:"Schiffer et al. — BigBrain lateral geniculate body six-layer dataset",url:"https://doi.org/10.25493/33Z0-BX",ja:"同一BigBrain標本の専門家参照と深層学習支援による左右6層分節です。公式フル変換で0.5 mm格子へ最近傍再標本化し、層の和集合だけを使用しています。CC BY-NC-SA 4.0。プロジェクトでの採用はAI照合で、専門家レビュー済みとは扱いません。",en:"Expert-reference and deep-learning-assisted six-layer segmentations of both lateral geniculate bodies in the same BigBrain specimen. The union of layers was resampled by nearest neighbour onto the 0.5 mm grid through the official full transform. CC BY-NC-SA 4.0. Project adoption was AI-assisted and is not treated as expert review."},
];
const readings = [
  {name:"Microsurgical anatomy of the sagittal stratum",url:"https://pubmed.ncbi.nlm.nih.gov/31363919/",ja:"視放線を周囲の白質束から区別するための矢状層の線維解剖比較。別標本の境界は転写していません。",en:"Fiber-anatomy comparison of the sagittal stratum used to distinguish the optic radiation from surrounding white-matter bundles. Boundaries from another specimen were not transferred."},
  {name:"Akeret et al. (2022) — Multimodal anatomy of the human forniceal commissure",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC9314404/",ja:"線維解剖と組織像による脳弓体部・脚・正中膜の位置関係を比較しました。別標本の境界は転写せず、臨床用途や微細交連の量を教材へ追加していません。",en:"Consulted for fiber-dissection and histological relationships among the fornix body, crura and midline membrane. Boundaries from other specimens were not transferred, and no new clinical use or quantitative claim about the fine commissure was added to the material."},
  {name:"Naidich et al. (1986) — Anterior commissure: anatomic-MR correlation",url:"https://pubmed.ncbi.nlm.nih.gov/3941867/",ja:"抄録を参照。前交連の正中部と左右へ曲がる走行の比較資料です。BigBrainで見える帯の同定を検討するために使用し、別標本の境界は転写していません。",en:"Abstract consulted for the midline anterior commissure and its curving bilateral course. Used to investigate the band visible in BigBrain; boundaries from another specimen were not transferred."},
  {name:"Barany et al. (2020; online 2019) — Neural and vascular architecture of the septum pellucidum",url:"https://pubmed.ncbi.nlm.nih.gov/31374555/",ja:"抄録を参照。透明中隔とその下方の中隔領域、脳弓の位置関係を比較。薄い膜の範囲と周辺組織を区別する資料で、個々の分節境界の出典ではありません。",en:"Abstract consulted for relationships between the septum pellucidum, the underlying septal region and the fornix. Used to distinguish the thin membrane from adjacent tissue, not as a source of individual segmentation boundaries."},
  {name:"Barany et al. (2024) — Topographical anatomy of the septum verum",url:"https://doi.org/10.1038/s41598-024-68464-x",ja:"線維解剖・組織学による中隔領域の位置関係を参照。透明中隔の下方付着部や脳弓との移行を、単純な膜や一本の線維として扱わないための比較資料です。",en:"Fiber-dissection and histological context for septal relationships. Used to avoid treating the inferior septal attachment and transition to the fornix as a simple membrane or single tract."},
  {name:"UAMS — Visceral Structures of the Head and Neck",url:"https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/viscera-tables/visceral-structures-of-the-head-and-neck/",ja:"V・IX・X・XIの概略出現部と近位走行の比較資料。模式モデルの配置検討に使用し、別標本の境界や座標を分節へ転写していません。",en:"Comparison for approximate attachment and proximal course of cranial nerves V, IX, X and XI. Used in schematic placement review; boundaries and coordinates from another specimen are not transferred into segmentation."},
  {name:"StatPearls — Neuroanatomy, Cranial Nerve 11 (Accessory)",url:"https://www.ncbi.nlm.nih.gov/books/NBK507722/",ja:"副神経の脊髄由来線維の上行と、表示範囲・省略の整理に使用。模式形状を標本から追跡した神経根とは扱っていません。",en:"Used to distinguish the ascent of spinal accessory fibers and clarify display scope and omissions. Schematic geometry is not treated as a root traced from the specimen."},
  {name:"Sonne et al. — Neuroanatomy, Cranial Nerve (StatPearls)",url:"https://www.ncbi.nlm.nih.gov/books/NBK470353/",ja:"V・IX・X・XIの機能要約の照合に使用。模式形状を調整中の項目にも機能説明を残しています。標本の分節境界や神経根座標の出典ではありません。",en:"Used to cross-check function summaries for cranial nerves V, IX, X and XI. Function descriptions remain available while schematic geometry is being adjusted. This is not a source of specimen segmentation boundaries or root coordinates."},
  {name:"UTHealth Neuroanatomy Online — Pons and trigeminal nerve",url:"https://nba.uth.tmc.edu/neuroanatomy/l4/Lab04p21_index.html",ja:"三叉神経の橋前外側出現部と感覚根・運動根の一般的位置関係を照合。BigBrainでの根の同定や置換形状の採用根拠ではありません。",en:"Consulted for the general anterolateral pontine emergence and sensory/motor roots of the trigeminal nerve. This does not identify the roots in BigBrain or establish replacement geometry."},
  {name:"Casamitjana et al. (2025) — NextBrain",url:"https://doi.org/10.1038/s41586-025-09708-2",ja:"別標本の組織学的アトラスとラベル一覧を調査。脳弓・内包・視覚路の部位区分を比較する資料で、BigBrainの境界として転写・採用していません。",en:"Investigation of a histological atlas of other specimens and its label catalogue, for comparing subdivisions of the fornix, internal capsule and visual pathway. No boundaries have been transferred to or adopted for BigBrain."},
  {name:"Rushmore et al. (2022) — Anatomically curated subcortical segmentation",url:"https://doi.org/10.3389/fnana.2022.894606",ja:"脳室間孔・第三脳室・大脳横裂の区分を照合。MRIの運用上の区画は組織学的な自然境界と同一ではなく、この規約やラベルをそのまま採用していません。",en:"Context for the interventricular foramina, third ventricle and transverse cerebral fissure. Operational MRI regions are not identical to histological boundaries; this protocol and its labels have not been adopted wholesale."},
  {name:"Iglesias et al. (2015) — Bayesian segmentation of brainstem structures in MRI",url:"https://doi.org/10.1016/j.neuroimage.2015.02.065",ja:"Appendix Bの中脳分節規約を照合。MRIの補助線を組織学的な自然境界とは扱わず、本標本へ境界を転写していません。",en:"Appendix B consulted for the midbrain delineation protocol. MRI reference lines are not treated as natural histological boundaries or transferred to this specimen."},
  {name:"Longatti et al. (2007) — Endoscopic anatomy of the cerebral aqueduct",url:"https://pubmed.ncbi.nlm.nih.gov/17876227/",ja:"抄録を参照。中脳水道の内形と後交連などの位置関係の背景資料です。内視鏡所見を本標本の境界へ転写していません。",en:"Abstract consulted for aqueduct morphology and landmarks including the posterior commissure. Endoscopic findings were not transferred to this specimen's boundaries."},
  {name:"Rubino & Hogg — Cerebral Aqueduct (StatPearls, updated 2023)",url:"https://www.ncbi.nlm.nih.gov/books/NBK540988/",ja:"解剖解説を参照。第三・第四脳室との移行を区別する補助資料で、原画像や採用マスクの出典ではありません。",en:"Anatomical background for distinguishing transitions to the third and fourth ventricles; not a source image or adopted mask."},
  {name:"Campos da Silva et al. (2024) — Stereotactic anatomy of the third ventricle",url:"https://doi.org/10.1007/s00276-024-03312-1",ja:"第三脳室底と漏斗陥凹の位置関係を照合。標本で失われた壁を推測で再建したり、文献からボクセル境界を転写したりする根拠にはしていません。",en:"Context for the third-ventricle floor and infundibular recess. Not a basis for reconstructing missing specimen walls or transferring voxel boundaries."},
  {name:"Nagata, Rhoton & Barry (1988) — Microsurgical anatomy of the choroidal fissure",url:"https://pubmed.ncbi.nlm.nih.gov/3394010/",ja:"抄録を参照。側脳室下角・海馬采・脳槽の位置関係の照合。文献からボクセル境界を転写していません。",en:"Abstract consulted for relationships between the temporal horn, fimbria and cisterns. Voxel boundaries were not transferred from this paper."},
  {name:"Oculomotor fascicular anatomy — PubMed 23242853",url:"https://pubmed.ncbi.nlm.nih.gov/23242853/",ja:"赤核の外形と内部線維を区別する参考。局所の白い帯の線維名を確定する根拠ではありません。",en:"Context for distinguishing the red-nucleus outline from internal fibres; not identification of a specific pale band."},
  {name:"Sitek et al. (2019) — Subcortical auditory system",url:"https://doi.org/10.7554/eLife.48932",ja:"聴覚路核アトラスの比較調査。教材との空間対応が未解決で、分節へ未採用です。",en:"Comparison with an auditory-nucleus atlas. Spatial correspondence remains unresolved; not adopted into the teaching segmentation."},
  {name:"Jones et al. (2020) — BigBrain Workshop",url:"https://bigbrainproject.org/docs/4th-bb-workshop/20-06-26-BigBrainWorkshop-Jones.pdf",ja:"脳弓周辺の調査資料。脳弓の完成分節を取得・採用したものではありません。",en:"Background investigation around the fornix; not an acquired or adopted complete fornix segmentation."},
  {name:"UTHealth Neuroanatomy Online — Limbic system",url:"https://nba.uth.tmc.edu/neuroanatomy/L11/Lab11p06_index.html",ja:"Papez回路の構成と歴史的位置づけを回路解説に使用。概念上の結合を標本由来形状として扱っていません。",en:"Used for the components and historical context of the Papez circuit. Conceptual connections are not treated as specimen-derived geometry."},
  {name:"StatPearls — Neuroanatomy, Limbic System",url:"https://www.ncbi.nlm.nih.gov/books/NBK538491/",ja:"Papez回路を含む辺縁系の構成と機能の照合に使用。回路概念をBigBrainの分節境界へ転写していません。",en:"Used to cross-check limbic-system organization and function, including the Papez circuit. Circuit concepts were not transferred to BigBrain segmentation boundaries."},
  {name:"Gupta et al. — Neuroanatomy, Visual Pathway (StatPearls)",url:"https://www.ncbi.nlm.nih.gov/books/NBK553189/",ja:"網膜から一次視覚野までの主経路、視交叉での部分交叉、外側膝状体と視放線の解説に使用。模式線維を実標本の分節とは区別しています。",en:"Used for the main retina-to-V1 route, partial crossing at the chiasm, lateral geniculate relay and optic radiation. Schematic fibers remain distinct from specimen segmentation."},
  {name:"Purves et al. — Circuits within the Basal Ganglia System",url:"https://www.ncbi.nlm.nih.gov/books/NBK10847/",ja:"直接路・間接路、脱抑制、視床下核から出力核への興奮性結合の解説に使用。概念図の線は分節・トラクト形状ではありません。",en:"Used for direct and indirect pathways, disinhibition and excitatory STN output to basal-ganglia output nuclei. Diagram lines are not segmented tract geometry."},
  {name:"Lanciego et al. (2012) — Functional neuroanatomy of the basal ganglia",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3543080/",ja:"基底核の並列回路とハイパー直接路を含む回路構成の照合に使用。",en:"Used to cross-check basal-ganglia circuit organization, including parallel and hyperdirect pathways."},
  {name:"The Superior Transvelar Approach to the Fourth Ventricle and Brainstem",url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3424008/",ja:"第四脳室上部と上髄帆・上小脳脚の位置関係の比較資料。BigBrainの個々の分節境界は原画像で確認し、別標本の境界を転写していません。",en:"Comparison for the superior fourth ventricle and the relationships of the superior medullary velum and superior cerebellar peduncles. Individual BigBrain segmentation boundaries were checked against the source images; boundaries from another specimen were not transferred."},
];

export function SegmentationReferences({english}:{english:boolean}) {
  return <section className="legalReferences" data-segmentation-references="true">
    <p data-cerebellar-representation="current-section-labels">{english?"The BigBrain cerebellum and brainstem shown in Sections are reconstructed from the current section labels. A local 197-voxel folial repair is included. Remaining gaps and isolated components have not been declared complete, and these section models are distinct from the MNI surface models.":"連続断面のBigBrain小脳・脳幹3Dは、断面と同じ現行ラベルから再構成しています。小脳葉の局所197点修正を反映していますが、残る塗り落としや孤立成分の確認は未完了です。MNIの脳表モデルとは区別しています。"}</p>
    <p data-brainstem-representation="partial-tissue-repair">{english?"The BigBrain brainstem label used in Sections includes a partial image-guided repair toward the cerebral peduncles. Its upper extent remains unresolved. It is not a completed segmentation or the separate MNI surface scaffold.":"断面用のBigBrain脳幹ラベルは、大脳脚側の塗り落としを原画像に基づき一部補修しています。上方の範囲は未確定で、全脳幹の完成分節でも、別のMNI脳表モデルそのものでもありません。"}</p>
    <p data-aqueduct-representation="partial-versus-schematic">{english?"The partial cerebral aqueduct in Sections is an image-guided BigBrain label (ID41), not the schematic aqueduct in the block specimen. Only part of the lumen is represented; its full extent and transition boundaries remain unconfirmed.":"断面画面の中脳水道候補（部分）はBigBrain画像誘導ラベルID41で、ブロック標本の模式中脳水道とは別です。腔の一部分だけを示し、全長と移行境界は未確定です。"}</p>
    <h3>{english?"References and use in this app":"参考文献と本アプリでの用途"}</h3>
    <p>{english?"Primary sources and selected review references. Citation does not imply author endorsement or completed expert review. Resolution and review coverage differ between repairs.":"主要な出典と照合資料です。引用元による承認や専門家レビュー完了を意味しません。使用解像度・確認範囲は修正ごとに異なります。"}</p>
    <h4>{english?"Source images, labels and surfaces":"原画像・ラベル・表面データ"}</h4>
    {sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a><br/>{english?s.en:s.ja}</p>)}
    <h4>{english?"Context and investigation — not adopted boundary data":"照合・調査資料 — 採用境界データではありません"}</h4>
    {readings.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.name}</a><br/>{english?s.en:s.ja}</p>)}
  </section>;
}
