import { createHash } from "node:crypto";
import { readFile, readdir, stat, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root=resolve(dirname(fileURLToPath(import.meta.url)),"..");
const dist=resolve(root,"dist");
async function walk(directory){
  const result=[];
  for(const entry of await readdir(directory,{withFileTypes:true})){
    const target=resolve(directory,entry.name);
    if(entry.isDirectory())result.push(...await walk(target));
    else result.push(target);
  }
  return result;
}
const files=await walk(dist);
const core=[];
const atlasBytes={};
for(const file of files){
  const name=relative(dist,file).split(sep).join("/");
  if(name==="sw.js")continue;
  const info=await stat(file);
  if(name.startsWith("atlas/")){atlasBytes[name]=info.size;continue}
  if(info.size<=2*1024*1024)core.push(name);
}
core.push("");
core.sort();
const builderSource=await readFile(fileURLToPath(import.meta.url),"utf8");
const signature=createHash("sha256").update(JSON.stringify(core)+await readFile(resolve(dist,"index.html"),"utf8")+builderSource).digest("hex").slice(0,12);
const source=`/* Generated by scripts/build_service_worker.mjs. */
const VERSION=${JSON.stringify(signature)};
const CORE_CACHE="brain-practical-core-"+VERSION;
const RUNTIME_CACHE="brain-practical-runtime-"+VERSION;
const PACK_CACHE="brain-practical-offline-packs";
const CORE_PATHS=${JSON.stringify(core)};
const scoped=path=>new URL(path,self.registration.scope).href;
const ATLAS_BYTES=new Map(Object.entries(${JSON.stringify(atlasBytes)}).map(([path,bytes])=>[scoped(path),bytes]));

self.addEventListener("install",event=>{
  event.waitUntil(caches.open(CORE_CACHE).then(cache=>cache.addAll(CORE_PATHS.map(scoped))).then(()=>self.skipWaiting()));
});
self.addEventListener("activate",event=>{
  event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key.startsWith("brain-practical-core-")&&key!==CORE_CACHE||key.startsWith("brain-practical-runtime-")&&key!==RUNTIME_CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()));
});
async function cached(request){return await caches.match(request,{ignoreSearch:false});}
function healthyAtlasResponse(request,response){
  if(!response.ok)return false;
  const contentType=(response.headers.get("Content-Type")||"").toLowerCase();
  if(contentType.includes("text/html"))return false;
  const key=new URL(request.url);key.search="";key.hash="";
  const expected=ATLAS_BYTES.get(key.href),contentEncoding=(response.headers.get("Content-Encoding")||"").toLowerCase(),contentLength=response.headers.get("Content-Length");
  return expected===undefined||contentLength===null||contentEncoding&&contentEncoding!=="identity"||Number(contentLength)===expected;
}
async function networkThenCache(request,cacheName,cacheable=response=>response.ok){
  try{
    const response=await fetch(request);
    if(cacheable(response)){const cache=await caches.open(cacheName);await cache.put(request,response.clone());}
    return response;
  }catch(error){const fallback=await cached(request);if(fallback)return fallback;throw error;}
}
self.addEventListener("fetch",event=>{
  const request=event.request;
  if(request.method!=="GET")return;
  const url=new URL(request.url);
  if(url.origin!==self.location.origin)return;
  if(request.mode==="navigate"){
    event.respondWith(networkThenCache(request,RUNTIME_CACHE).catch(()=>caches.match(scoped("index.html"))));
    return;
  }
  if(url.pathname.endsWith("/offline-packs.json")){
    event.respondWith(networkThenCache(request,RUNTIME_CACHE).catch(()=>caches.match(scoped("offline-packs.json"))));
    return;
  }
  if(url.pathname.includes("/atlas/")){
    if(request.cache==="reload"){event.respondWith(fetch(request));return;}
    event.respondWith(caches.open(PACK_CACHE).then(cache=>cache.match(request)).then(hit=>hit&&healthyAtlasResponse(request,hit)?hit:networkThenCache(request,RUNTIME_CACHE,response=>healthyAtlasResponse(request,response))));
    return;
  }
  event.respondWith(caches.match(request).then(hit=>hit||networkThenCache(request,RUNTIME_CACHE)));
});
`;
await writeFile(resolve(dist,"sw.js"),source,"utf8");
console.log(`Generated sw.js ${signature}: ${core.length} shell resources`);
