export type AnatomyReviewRecordScopeValue = "not-selected" | string;
export type AnatomyReviewRecordCheckKey = "anatomical-correspondence" | "naming-and-laterality" | "learner-facing-presentation";
export type AnatomyReviewRecordOutcome = "not-assessed" | "no-concern-observed" | "concern-observed" | "unable-to-assess";
export type AnatomyReviewRecordConcernCode = "boundary-or-position" | "laterality" | "naming" | "continuity-or-topology" | "representation-source-mismatch" | "visibility-or-occlusion" | "learner-target-ambiguity" | "source-evidence-insufficient";
export type AnatomyReviewRecordSource = {path: "public/atlas/structure-provenance.json";schemaVersion: number;updated: string;registrySha256: string;entryKey: string;entrySha256: string};
export type AnatomyReviewRecordDraft = {
  schemaVersion: 1;
  recordType: "anatomy-review-record-draft";
  privacy: "no-identity-or-contact-data-recorded";
  status: "local-unsubmitted-draft";
  sourceRegistry: AnatomyReviewRecordSource;
  scope: {learnerSurface: AnatomyReviewRecordScopeValue;representation: AnatomyReviewRecordScopeValue};
  checks: {key: AnatomyReviewRecordCheckKey;outcome: AnatomyReviewRecordOutcome;concernCodes: AnatomyReviewRecordConcernCode[]}[];
  createdAt: string;
  updatedAt: string;
  adoptionDecision: "not-recorded";
  expertReviewStatus: "not-claimed";
};
export type AnatomyReviewRecordExport = AnatomyReviewRecordDraft & {exportedAt: string;completeness: {scopeSelected: boolean;assessedCheckCount: number;checkTotal: 3;concernsRecorded: boolean};submissionStatus: "not-submitted";registryMatch: "current"};
export const ANATOMY_REVIEW_RECORD_SCHEMA_VERSION: 1;
export const ANATOMY_REVIEW_RECORD_TYPE: "anatomy-review-record-draft";
export const ANATOMY_REVIEW_RECORD_STATUS: "local-unsubmitted-draft";
export const ANATOMY_REVIEW_RECORD_PRIVACY: "no-identity-or-contact-data-recorded";
export const ANATOMY_REVIEW_RECORD_STORAGE_PREFIX: string;
export const ANATOMY_REVIEW_RECORD_SOURCE_PATH: "public/atlas/structure-provenance.json";
export const ANATOMY_REVIEW_RECORD_SENTINEL_SCOPE: "not-selected";
export const ANATOMY_REVIEW_RECORD_CHECK_KEYS: readonly AnatomyReviewRecordCheckKey[];
export const ANATOMY_REVIEW_RECORD_CHECK_LABELS: Readonly<Record<AnatomyReviewRecordCheckKey,string>>;
export const ANATOMY_REVIEW_RECORD_OUTCOMES: readonly AnatomyReviewRecordOutcome[];
export const ANATOMY_REVIEW_RECORD_OUTCOME_LABELS: Readonly<Record<AnatomyReviewRecordOutcome,string>>;
export const ANATOMY_REVIEW_RECORD_CONCERN_CODES: readonly AnatomyReviewRecordConcernCode[];
export const ANATOMY_REVIEW_RECORD_CONCERN_LABELS: Readonly<Record<AnatomyReviewRecordConcernCode,string>>;
export const ANATOMY_REVIEW_RECORD_LOCK_REASONS: readonly string[];
export function canonicalAnatomyReviewJson(value: unknown): string;
export async function sha256Canonical(value: unknown): Promise<string>;
export function anatomyReviewRecordStorageKey(entryKey: string): string;
export function shouldApplyAnatomyReviewDraftRevision(completedRevision: number,latestRevision: number): boolean;
export function nextAnatomyReviewDraftRevision(currentRevision: number): number;
export function anatomyReviewStorageSnapshotMatches(actual: string|null|undefined,expected: string|null|undefined): boolean;
export async function createAnatomyReviewRecordDraft(registry: Record<string,unknown>,entryKey: string,now?: string): Promise<AnatomyReviewRecordDraft>;
export async function validateAnatomyReviewRecordDraft(value: unknown,registry: Record<string,unknown>): Promise<{ok:boolean;errors:string[];lockReason:string|null}>;
export async function inspectAnatomyReviewRecordStorage(serialized: string|undefined,registry: Record<string,unknown>,entryKey: string,now?: string): Promise<{state:"ready"|"locked";draft:AnatomyReviewRecordDraft|null;storageKey:string;errors:string[];reason?:string}>;
export function updateAnatomyReviewRecordScope(draft: AnatomyReviewRecordDraft,learnerSurface: AnatomyReviewRecordScopeValue,representation: AnatomyReviewRecordScopeValue,now?: string): AnatomyReviewRecordDraft;
export function updateAnatomyReviewRecordCheck(draft: AnatomyReviewRecordDraft,checkKey: AnatomyReviewRecordCheckKey,outcome: AnatomyReviewRecordOutcome,concernCodes?: AnatomyReviewRecordConcernCode[],now?: string): AnatomyReviewRecordDraft;
export async function buildAnatomyReviewRecordExport(draft: AnatomyReviewRecordDraft,registry: Record<string,unknown>,exportedAt?: string): Promise<AnatomyReviewRecordExport>;
export async function validateAnatomyReviewRecordExport(value: unknown,registry: Record<string,unknown>): Promise<{ok:boolean;errors:string[];summary:{scopeSelected:boolean;assessedCheckCount:number;checkTotal:3;concernsRecorded:boolean};lockReason:string|null}>;
