const latinToEnglish = Object.freeze({
  "Aqueductus mesencephali": "Cerebral aqueduct",
  "Areae vestibulares": "Vestibular areas",
  "Bulbus et tractus olfactorius": "Olfactory bulb and tract",
  "Capsula interna": "Internal capsule",
  "Chiasma et tractus optici (atlas candidate)": "Optic chiasm and tracts (atlas candidate)",
  "Colliculi faciales": "Facial colliculi",
  "Colliculi inferiores": "Inferior colliculi",
  "Colliculi superiores": "Superior colliculi",
  "Cornu inferius": "Inferior horn",
  "Corpora geniculata lateralia": "Lateral geniculate bodies",
  "Corpora geniculata medialia": "Medial geniculate bodies",
  "Corpora mamillaria": "Mammillary bodies",
  "Corpus amygdaloideum": "Amygdala",
  "Cortex entorhinalis": "Entorhinal cortex",
  "Cortex insularis": "Insular cortex",
  "Cortex occipitalis lateralis": "Lateral occipital cortex",
  "Cortex orbitofrontalis": "Orbitofrontal cortex",
  "Cortex pericalcarinus": "Pericalcarine cortex",
  "Fissura longitudinalis cerebri": "Longitudinal cerebral fissure",
  "Fossa interpeduncularis": "Interpeduncular fossa",
  "Globus pallidus externus": "External globus pallidus (GPe)",
  "Globus pallidus internus": "Internal globus pallidus (GPi)",
  "Gyri temporales transversi": "Transverse temporal gyri",
  "Gyrus cinguli": "Cingulate gyrus",
  "Gyrus frontalis medius, pars caudalis": "Caudal middle frontal gyrus",
  "Gyrus frontalis medius, pars rostralis": "Rostral middle frontal gyrus",
  "Gyrus frontalis superior": "Superior frontal gyrus",
  "Gyrus fusiformis": "Fusiform gyrus",
  "Gyrus lingualis": "Lingual gyrus",
  "Gyrus parahippocampalis": "Parahippocampal gyrus",
  "Gyrus postcentralis": "Postcentral gyrus",
  "Gyrus precentralis": "Precentral gyrus",
  "Gyrus supramarginalis": "Supramarginal gyrus",
  "Gyrus temporalis inferior": "Inferior temporal gyrus",
  "Gyrus temporalis medius": "Middle temporal gyrus",
  "Gyrus temporalis superior": "Superior temporal gyrus",
  "Lobulus paracentralis": "Paracentral lobule",
  "Lobulus parietalis inferior": "Inferior parietal lobule",
  "Lobulus parietalis superior": "Superior parietal lobule",
  "Mesencephalon": "Midbrain",
  "N. opticus / chiasma / tractus": "Optic nerve / chiasm / tract",
  "Nuclei rubri": "Red nuclei",
  "Nucleus caudatus": "Caudate nucleus",
  "Nucleus ruber": "Red nucleus",
  "Nucleus subthalamicus": "Subthalamic nucleus",
  "Olivae": "Olives",
  "Pars opercularis et triangularis": "Opercular and triangular parts",
  "Pars orbitalis gyri frontalis inferioris": "Orbital part of the inferior frontal gyrus",
  "Pedunculi cerebri": "Cerebral peduncles",
  "Pedunculus cerebellaris inferior": "Inferior cerebellar peduncle",
  "Pedunculus cerebellaris medius": "Middle cerebellar peduncle",
  "Pedunculus cerebellaris superior": "Superior cerebellar peduncle",
  "Plexus choroideus": "Choroid plexus",
  "Pyramides medullae oblongatae": "Medullary pyramids",
  "Radiatio acustica": "Auditory radiation",
  "Radiatio optica": "Optic radiation",
  "Substantia perforata anterior": "Anterior perforated substance",
  "Sulcus calcarinus": "Calcarine sulcus",
  "Sulcus centralis": "Central sulcus",
  "Sulcus frontalis superior": "Superior frontal sulcus",
  "Sulcus lateralis": "Lateral sulcus",
  "Sulcus olfactorius": "Olfactory sulcus",
  "Sulcus parietooccipitalis": "Parieto-occipital sulcus",
  "Sulcus precentralis": "Precentral sulcus",
  "Trigona nervi hypoglossi": "Hypoglossal trigones",
  "Trigona nervi vagi": "Vagal trigones",
  "Truncus encephali": "Brainstem",
  "Ventriculi laterales": "Lateral ventricles",
  "Ventriculus lateralis": "Lateral ventricle",
  "Ventriculus quartus": "Fourth ventricle",
  "Ventriculus tertius": "Third ventricle",
});

export function anatomyDisplayEnglish(value) {
  return latinToEnglish[value] ?? value;
}

export const translatedLatinAnatomyTerms = Object.freeze(Object.keys(latinToEnglish));
