const bilingual = (ja, en) => Object.freeze({ja, en});

export const CIRCUIT_TEACHING = Object.freeze({
  papez: Object.freeze({
    key: "papez",
    name: bilingual("Papez回路", "Papez circuit"),
    goal: bilingual("記憶に関わる内側側頭葉―間脳―帯状回の環状のつながりを、標本で確認できる構造と未分節の中継部に分けて説明できる。", "Explain the memory-related loop linking the medial temporal lobe, diencephalon and cingulate region, while separating structures visible in this specimen from unsegmented relays."),
    role: bilingual("海馬体から間脳と帯状回を経て内側側頭葉へ戻る結合を示す歴史的な回路モデルです。現在は記憶ネットワークを理解する基本図として使われますが、記憶や情動をこの一回路だけで説明するものではありません。", "A historical circuit model linking the hippocampal formation through diencephalic and cingulate relays back to the medial temporal lobe. It remains a useful framework for memory networks, but does not by itself explain memory or emotion."),
    paths: Object.freeze([
      Object.freeze({key:"loop", label:bilingual("情報の流れ（簡略）", "Information flow (simplified)"), kind:"relay", nodes:Object.freeze(["hippocampus","fornix","mammillary","mammillothalamic","anterior-thalamus","cingulate","cingulum","entorhinal","hippocampus"])})
    ]),
    nodes: Object.freeze([
      Object.freeze({key:"hippocampus", label:bilingual("海馬体", "Hippocampal formation"), detail:bilingual("内側側頭葉で新しい出来事の記憶形成に関わり、主な出力が脳弓へ向かいます。", "Supports formation of new episodic memories in the medial temporal lobe; a major output travels in the fornix."), specimen:bilingual("冠状断の海馬ラベルを観察できます。", "An existing hippocampal label can be inspected in a coronal section."), limitation:bilingual("海馬台・歯状回などの内部区分はこの段階図で描き分けません。", "Internal subdivisions such as the subiculum and dentate gyrus are not separated in this stage diagram."), observationIndex:0}),
      Object.freeze({key:"fornix", label:bilingual("脳弓", "Fornix"), detail:bilingual("海馬表面の白板の線維が内側で海馬采へ集まり、後方で脳弓脚へ続きます。脳弓は海馬体から乳頭体・中隔領域などへ向かう主要な白質路です。", "Alvear fibers on the hippocampal surface gather medially into the fimbria and continue posteriorly into the fornix crus. The fornix is a major white-matter output pathway toward the mammillary and septal regions."), specimen:bilingual("同一標本から追った体部・脚・柱と両側海馬采の部分分節を断面と3Dで観察できます。", "Partial body, crura, columns and bilateral fimbria traced in the same specimen can be inspected in sections and 3D."), limitation:bilingual("交連後の下行部は乳頭体に接する位置まで概略収録しています。海馬采全長と精密な終端境界・全外縁は未収録です。概略分節であり、脳弓全体の完成や専門家確認を意味しません。", "The postcommissural descent is approximately segmented to the mammillary bodies. Full fimbria, precise terminal boundaries and complete outer boundaries remain unrecorded. Approximate segmentation is neither a complete fornix nor expert validation."), observationIndex:1}),
      Object.freeze({key:"mammillary", label:bilingual("乳頭体", "Mammillary bodies"), detail:bilingual("海馬体からの入力を受け、乳頭視床路を介して視床前部へ中継します。", "Receive hippocampal-system input and relay toward the anterior thalamus through the mammillothalamic tract."), specimen:bilingual("水平断で、視床下部の腹側に並ぶ左右の乳頭体を探します。", "In a horizontal section, look for the paired mammillary bodies on the ventral side of the hypothalamus."), limitation:bilingual("プロジェクト内採用済みですが、専門家レビューは未完了です。", "Adopted within the project; expert review remains incomplete."), observationIndex:2}),
      Object.freeze({key:"mammillothalamic", label:bilingual("乳頭視床路", "Mammillothalamic tract"), detail:bilingual("乳頭体から視床前部核へ向かう線維束です。", "A fiber bundle projecting from the mammillary bodies to the anterior thalamic nuclei."), specimen:bilingual("乳頭体と視床の間を結ぶ方向を概念図で追います。", "Follow its direction between the mammillary bodies and thalamus in the concept diagram."), limitation:bilingual("現行ラベル・3Dには収録していません。", "Not included in the current labels or 3D model."), observationIndex:null}),
      Object.freeze({key:"anterior-thalamus", label:bilingual("視床前部核", "Anterior thalamic nuclei"), detail:bilingual("乳頭体からの入力を受け、帯状回へ投射する中継核群です。", "A relay group receiving mammillary input and projecting toward cingulate cortex."), specimen:bilingual("視床全体の位置を代用の目安として観察できます。", "The whole-thalamus label can be inspected only as a positional reference."), limitation:bilingual("視床前部核そのものは未分節です。視床全体の着色を前部核と解釈しないでください。", "The anterior nuclei themselves are unsegmented; do not interpret the whole-thalamus highlight as an anterior-nucleus label."), observationIndex:3}),
      Object.freeze({key:"cingulate", label:bilingual("帯状回", "Cingulate gyrus"), detail:bilingual("視床前部から入力を受け、内側側頭葉へ向かう皮質ネットワークに関わります。", "Receives anterior thalamic input and participates in cortical connections toward the medial temporal lobe."), specimen:bilingual("アトラス対応の帯状回領域を3Dで観察できます。", "An atlas-mapped cingulate region can be inspected in 3D."), limitation:bilingual("皮質領域はBigBrain同一標本の組織学的手動分節ではありません。", "The cortical region is not a same-specimen histological manual segmentation."), observationIndex:4}),
      Object.freeze({key:"cingulum", label:bilingual("帯状束", "Cingulum"), detail:bilingual("帯状回周囲と海馬傍回・嗅内野を結ぶ長い連合線維系です。", "A long association-fiber system linking cingulate regions with parahippocampal and entorhinal regions."), specimen:bilingual("帯状回から海馬傍回へ向かう方向を概念図で追います。", "Follow its direction from the cingulate toward the parahippocampal region in the concept diagram."), limitation:bilingual("現行ラベル・3Dには収録していません。", "Not included in the current labels or 3D model."), observationIndex:null}),
      Object.freeze({key:"entorhinal", label:bilingual("海馬傍回・嗅内野", "Parahippocampal and entorhinal cortex"), detail:bilingual("皮質から海馬体への主要な入口を含み、回路を内側側頭葉へ戻します。", "Includes a major cortical gateway into the hippocampal formation, returning the simplified loop to the medial temporal lobe."), specimen:bilingual("アトラス対応領域を3Dで観察できます。", "Atlas-mapped regions can be inspected in 3D."), limitation:bilingual("嗅内野と海馬傍回の境界は本標本由来の確定分節ではありません。", "The entorhinal–parahippocampal boundary is not a validated specimen-derived segmentation."), observationIndex:5}),
    ]),
    displayLimit:bilingual("この図は古典的Papez回路を学ぶための簡略図です。実際の記憶ネットワークには追加の結合があり、矢印の太さは結合強度を示しません。", "This is a simplified teaching diagram of the classical Papez circuit. Memory networks contain additional connections, and arrow width does not encode connection strength."),
    sources:Object.freeze([
      Object.freeze({label:"UTHealth Neuroanatomy Online — Limbic system", url:"https://nba.uth.tmc.edu/neuroanatomy/L11/Lab11p06_index.html"}),
      Object.freeze({label:"NCBI Bookshelf — Limbic System", url:"https://www.ncbi.nlm.nih.gov/books/NBK538491/"}),
    ]),
  }),
  visual: Object.freeze({
    key:"visual",
    name:bilingual("視覚路", "Visual pathway"),
    goal:bilingual("左右の網膜由来線維が視交叉で部分交叉し、各視索から視床・視放線を経て反対側視野の情報を一次視覚野へ送る流れを説明できる。", "Explain how retinal fibers partially cross at the optic chiasm so that each optic tract carries the opposite visual field through the thalamus and optic radiation to primary visual cortex."),
    role:bilingual("網膜で生じた視覚信号を、視神経・視交叉・視索・外側膝状体・視放線を経て一次視覚野へ運びます。", "Carries retinal visual signals through the optic nerve, chiasm, tract, lateral geniculate nucleus and optic radiation to primary visual cortex."),
    paths:Object.freeze([
      Object.freeze({key:"left-field-left-eye", label:bilingual("左視野・左眼鼻側網膜：交叉して右半球へ", "Left visual field · left nasal retina: crosses to the right hemisphere"), kind:"crossed", nodes:Object.freeze(["retina","optic-nerve","optic-chiasm","optic-tract","lgn","optic-radiation","v1"]), labels:Object.freeze([bilingual("左眼鼻側網膜","Left nasal retina"),bilingual("左視神経","Left optic nerve"),bilingual("視交叉（交叉）","Chiasm (crosses)"),bilingual("右視索","Right optic tract"),bilingual("右外側膝状体","Right LGN"),bilingual("右視放線","Right optic radiation"),bilingual("右V1","Right V1")])}),
      Object.freeze({key:"left-field-right-eye", label:bilingual("左視野・右眼耳側網膜：同側の右半球へ", "Left visual field · right temporal retina: remains in the right hemisphere"), kind:"uncrossed", nodes:Object.freeze(["retina","optic-nerve","optic-chiasm","optic-tract","lgn","optic-radiation","v1"]), labels:Object.freeze([bilingual("右眼耳側網膜","Right temporal retina"),bilingual("右視神経","Right optic nerve"),bilingual("視交叉（非交叉）","Chiasm (uncrossed)"),bilingual("右視索","Right optic tract"),bilingual("右外側膝状体","Right LGN"),bilingual("右視放線","Right optic radiation"),bilingual("右V1","Right V1")])}),
      Object.freeze({key:"right-field-right-eye", label:bilingual("右視野・右眼鼻側網膜：交叉して左半球へ", "Right visual field · right nasal retina: crosses to the left hemisphere"), kind:"crossed", nodes:Object.freeze(["retina","optic-nerve","optic-chiasm","optic-tract","lgn","optic-radiation","v1"]), labels:Object.freeze([bilingual("右眼鼻側網膜","Right nasal retina"),bilingual("右視神経","Right optic nerve"),bilingual("視交叉（交叉）","Chiasm (crosses)"),bilingual("左視索","Left optic tract"),bilingual("左外側膝状体","Left LGN"),bilingual("左視放線","Left optic radiation"),bilingual("左V1","Left V1")])}),
      Object.freeze({key:"right-field-left-eye", label:bilingual("右視野・左眼耳側網膜：同側の左半球へ", "Right visual field · left temporal retina: remains in the left hemisphere"), kind:"uncrossed", nodes:Object.freeze(["retina","optic-nerve","optic-chiasm","optic-tract","lgn","optic-radiation","v1"]), labels:Object.freeze([bilingual("左眼耳側網膜","Left temporal retina"),bilingual("左視神経","Left optic nerve"),bilingual("視交叉（非交叉）","Chiasm (uncrossed)"),bilingual("左視索","Left optic tract"),bilingual("左外側膝状体","Left LGN"),bilingual("左視放線","Left optic radiation"),bilingual("左V1","Left V1")])}),
    ]),
    nodes:Object.freeze([
      Object.freeze({key:"retina", label:bilingual("網膜", "Retina"), detail:bilingual("光を神経信号へ変換し、網膜神経節細胞の軸索が視神経を作ります。", "Converts light into neural signals; retinal ganglion-cell axons form the optic nerve."), specimen:bilingual("眼球・網膜は表示範囲外です。", "The globe and retina are outside the displayed specimen."), limitation:bilingual("概念図の開始点としてのみ示します。", "Shown only as the conceptual starting point."), observationIndex:null}),
      Object.freeze({key:"optic-nerve", label:bilingual("視神経", "Optic nerve"), detail:bilingual("片眼の網膜神経節細胞の軸索を視交叉へ運びます。", "Carries retinal ganglion-cell axons from one eye toward the optic chiasm."), specimen:bilingual("脳底面のII模式3Dで近位部を観察できます。", "A proximal schematic segment can be inspected in the basal-view cranial-nerve layer."), limitation:bilingual("眼窩内の全長や個々の線維は再現していません。", "The full intraorbital course and individual fibers are not represented."), observationIndex:0, observationKind:"schematic"}),
      Object.freeze({key:"optic-chiasm", label:bilingual("視交叉", "Optic chiasm"), detail:bilingual("鼻側網膜の線維は交叉し、耳側網膜の線維は同側を進みます。", "Nasal retinal fibers cross, while temporal retinal fibers remain ipsilateral."), specimen:bilingual("原画像から収録した視交叉中央部を断面と3Dで観察できます。", "The source-traced central chiasm can be inspected in sections and 3D."), limitation:bilingual("部分分節です。左右視索の主なラベルへ連続しますが、交叉・非交叉線維や視神経側の全外縁は示しません。専門家未確認です。", "This is a partial segmentation. It continues into the main optic-tract labels, but does not show crossed or uncrossed fibers or complete nerve-side margins. It is not expert-reviewed."), observationIndex:1}),
      Object.freeze({key:"optic-tract", label:bilingual("視索", "Optic tract"), detail:bilingual("両眼からの反対側視野の情報をまとめ、主に外側膝状体へ送ります。", "Combines information from the opposite visual field of both eyes and projects mainly to the lateral geniculate nucleus."), specimen:bilingual("原画像から追った左右視索の部分分節を断面と3Dで観察できます。表面側の帯は同一標本の外側膝状体に接します。", "Source-traced partial left and right optic tracts can be inspected in sections and 3D. Their surface bands contact the same-specimen lateral geniculate labels."), limitation:bilingual("深部側と終端の境界は教材用の概略です。個々の線維、網膜対応、視放線はこの分節に含みません。専門家未確認です。", "Deep and terminal boundaries are approximate teaching boundaries. Individual fibers, retinotopy and optic radiations are not included. Not expert-reviewed."), observationIndex:2}),
      Object.freeze({key:"lgn", label:bilingual("外側膝状体", "Lateral geniculate nucleus"), detail:bilingual("視床後部にある主要な視覚中継核で、網膜対応を保って視放線へ送ります。", "The major visual relay in the posterior thalamus, preserving retinotopic organization for transmission into the optic radiation."), specimen:bilingual("同一BigBrain標本から再標本化した左右外側膝状体ラベルを断面で観察できます。", "The left and right lateral geniculate labels resampled from the same BigBrain specimen can be inspected in sections."), limitation:bilingual("視索表面側の帯との接点は収録しましたが、視放線は未分節です。視覚路全体が連続分節されたことは意味しません。", "Contact with the optic-tract surface bands is included, but optic radiations remain unsegmented. This does not establish a continuous segmentation of the entire visual pathway."), observationIndex:3}),
      Object.freeze({key:"optic-radiation", label:bilingual("視放線", "Optic radiation"), detail:bilingual("外側膝状体から後頭葉の一次視覚野へ広がる膝状体鳥距路です。", "The geniculocalcarine projection spreading from the lateral geniculate nucleus to primary visual cortex."), specimen:bilingual("プリセット選択中は、手作業配置の模式3Dで大まかな方向を観察できます。", "While this preset is active, a hand-positioned schematic 3D layer shows the approximate direction."), limitation:bilingual("Meyer loopを含む個体の線維走行・太さ・網膜対応を再現していません。原画像から追跡した線維束ではなく、走行方向の模式表示です。", "Individual fiber trajectories, thickness, retinotopy and the Meyer loop are not reconstructed. This is a schematic direction guide, not a fiber bundle traced from raw images."), observationIndex:4, observationKind:"schematic"}),
      Object.freeze({key:"v1", label:bilingual("一次視覚野（V1）", "Primary visual cortex (V1)"), detail:bilingual("鳥距溝の両岸で視覚情報を最初に皮質処理し、視野の空間配置を保ちます。", "Provides the first cortical stage of visual processing along the banks of the calcarine sulcus while preserving visual-field organization."), specimen:bilingual("鳥距溝周囲のアトラス対応皮質を3Dで観察できます。", "Atlas-mapped cortex around the calcarine sulcus can be inspected in 3D."), limitation:bilingual("V1の組織学的境界や網膜対応をこのモデルで確定しません。", "This model does not establish histological V1 boundaries or retinotopic maps."), observationIndex:5}),
    ]),
    displayLimit:bilingual("左右の視野について、両眼の鼻側／耳側網膜線維を4行に分けた模式図です。行と文字で交叉・非交叉を示し、色だけには依存しません。側枝・層構造・正確な線維数や太さは表しません。", "The four rows distinguish nasal and temporal retinal fibers from both eyes for the left and right visual fields. Crossing and uncrossed routes are stated in text rather than encoded by color alone. Collaterals, laminae, exact fiber counts and thickness are omitted."),
    sources:Object.freeze([
      Object.freeze({label:"UTHealth Neuroscience Online — Visual Processing: Cortical Pathways", url:"https://nba.uth.tmc.edu/neuroscience/s2/chapter15.html"}),
      Object.freeze({label:"NCBI Bookshelf — Neuroanatomy, Visual Pathway", url:"https://www.ncbi.nlm.nih.gov/books/NBK553189/"}),
    ]),
  }),
  "basal-ganglia": Object.freeze({
    key:"basal-ganglia",
    name:bilingual("大脳基底核回路", "Basal ganglia circuits"),
    goal:bilingual("直接路・間接路・ハイパー直接路の分岐と、各結合の興奮性／抑制性をたどり、視床への出力が運動選択をどう調節するか説明できる。", "Trace the direct, indirect and hyperdirect branches with their excitatory or inhibitory connections, and explain how basal-ganglia output regulates thalamocortical activity during action selection."),
    role:bilingual("皮質からの入力を線条体・淡蒼球・視床下核・黒質で処理し、視床皮質活動を調節して、選んだ行動を通し競合する行動を抑えるネットワークです。", "Processes cortical input through the striatum, pallidum, subthalamic nucleus and substantia nigra to regulate thalamocortical activity, facilitating selected actions and suppressing competing actions."),
    paths:Object.freeze([
      Object.freeze({key:"direct", label:bilingual("直接路：選択した出力を通しやすくする", "Direct pathway: facilitates selected output"), kind:"mixed", nodes:Object.freeze(["cortex","striatum","gpi-snr","thalamus","cortex"]), signs:Object.freeze(["+","−","−","+"])}),
      Object.freeze({key:"indirect", label:bilingual("間接路：競合する出力を抑えやすくする", "Indirect pathway: suppresses competing output"), kind:"mixed", nodes:Object.freeze(["cortex","striatum","gpe","stn","gpi-snr","thalamus","cortex"]), signs:Object.freeze(["+","−","−","+","−","+"])}),
      Object.freeze({key:"hyperdirect", label:bilingual("ハイパー直接路：皮質から出力核へ速く制動をかける", "Hyperdirect pathway: rapid cortical braking through the output nuclei"), kind:"mixed", nodes:Object.freeze(["cortex","stn","gpi-snr","thalamus","cortex"]), signs:Object.freeze(["+","+","−","+"])})
    ]),
    nodes:Object.freeze([
      Object.freeze({key:"cortex", label:bilingual("大脳皮質", "Cerebral cortex"), detail:bilingual("線条体と視床下核へ興奮性入力を送り、視床から興奮性入力を受けます。", "Sends excitatory input to the striatum and subthalamic nucleus and receives excitatory thalamic input."), specimen:bilingual("脳表で大脳皮質の広がりを見て、深部の線条体・視床との位置関係を確かめます。", "Use the brain-surface view to locate the cortex relative to the deeper striatum and thalamus."), limitation:bilingual("運動・前頭皮質の領域差はこの図では省略します。", "Differences among motor and frontal cortical territories are omitted."), observationIndex:null}),
      Object.freeze({key:"striatum", label:bilingual("線条体（尾状核・被殻）", "Striatum (caudate and putamen)"), detail:bilingual("皮質入力を受け、直接路ではGPi/SNr、間接路ではGPeへ抑制性出力を送ります。", "Receives cortical input and sends inhibitory output to GPi/SNr in the direct pathway and to GPe in the indirect pathway."), specimen:bilingual("尾状核と被殻の既存ラベルを3D・断面で同期観察できます。", "Existing caudate and putamen labels can be inspected in synchronized 3D and section views."), limitation:bilingual("線条体内部の細胞型・機能領域は描き分けません。", "Striatal cell types and functional territories are not separated."), observationIndex:0}),
      Object.freeze({key:"gpe", label:bilingual("淡蒼球外節（GPe）", "External globus pallidus (GPe)"), detail:bilingual("視床下核を持続的に抑制し、間接路で線条体から抑制される中継部です。", "Tonically inhibits the subthalamic nucleus and is itself inhibited by the striatum in the indirect pathway."), specimen:bilingual("淡蒼球外節の既存ラベルを観察できます。", "An existing GPe label can be inspected."), limitation:bilingual("微細な核内区分や線維は表示しません。", "Fine intranuclear subdivisions and fibers are not displayed."), observationIndex:1}),
      Object.freeze({key:"stn", label:bilingual("視床下核（STN）", "Subthalamic nucleus (STN)"), detail:bilingual("GPeからの抑制と皮質からの興奮を受け、GPi/SNrへ興奮性出力を送ります。", "Receives inhibition from GPe and excitation from cortex, and sends excitatory output to GPi/SNr."), specimen:bilingual("視床下核の既存ラベルを3D・断面で観察できます。", "An existing STN label can be inspected in 3D and section views."), limitation:bilingual("結合線そのものは標本由来表示ではありません。", "The connections themselves are not specimen-derived geometry."), observationIndex:2}),
      Object.freeze({key:"gpi-snr", label:bilingual("GPi／SNr（出力核）", "GPi/SNr (output nuclei)"), detail:bilingual("視床を持続的に抑制する主要出力核です。直接路はこの抑制を弱め、間接路・ハイパー直接路は強める方向に働きます。", "Major output nuclei that tonically inhibit the thalamus. The direct pathway reduces this inhibition, whereas indirect and hyperdirect routes tend to increase it."), specimen:bilingual("淡蒼球段階でGPiを、黒質段階でSNrを含む既存黒質ラベルを別々に観察できます。", "GPi can be inspected at the pallidal stage, and the separate substantia-nigra stage shows the existing label that contains SNr."), limitation:bilingual("黒質はSNrとSNcを分けておらず、GPiとSNrを一つの実ラベルとして示すものでもありません。", "The substantia nigra label does not separate SNr from SNc, and GPi/SNr are not a single specimen label."), observationIndex:1, observations:Object.freeze([Object.freeze({label:bilingual("GPiを標本で見る","Inspect GPi"),index:1}),Object.freeze({label:bilingual("黒質（SNrを含む）を見る","Inspect substantia nigra (includes SNr)"),index:3})])}),
      Object.freeze({key:"thalamus", label:bilingual("視床", "Thalamus"), detail:bilingual("基底核出力核から抑制を受け、皮質へ興奮性入力を返します。出力核の抑制が弱まると対応する視床皮質活動が通りやすくなります。", "Receives inhibitory basal-ganglia output and returns excitation to cortex. Reduced output-nucleus inhibition permits greater activity in the corresponding thalamocortical channel."), specimen:bilingual("視床全体の既存ラベルを位置の目安として観察できます。", "The existing whole-thalamus label can be inspected as a positional reference."), limitation:bilingual("VA/VLなど運動関連核を独立分節していません。", "Motor-related nuclei such as VA/VL are not independently segmented."), observationIndex:4}),
    ]),
    displayLimit:bilingual("＋は興奮性、−は抑制性結合を示します。これは主要な古典回路の簡略図で、各核の並列チャネル、局所回路、ドパミン作用の細部を省略しています。", "+ indicates excitation and − inhibition. This simplified canonical diagram omits parallel channels, local circuits and details of dopaminergic modulation."),
    sources:Object.freeze([
      Object.freeze({label:"UTHealth Neuroscience Online — Basal Ganglia", url:"https://nba.uth.tmc.edu/neuroscience/s3/chapter04.html"}),
      Object.freeze({label:"NCBI Bookshelf — Circuits within the Basal Ganglia System", url:"https://www.ncbi.nlm.nih.gov/books/NBK10847/"}),
      Object.freeze({label:"Lanciego et al. (2012) — Functional neuroanatomy of the basal ganglia", url:"https://pmc.ncbi.nlm.nih.gov/articles/PMC3543080/"}),
    ]),
  }),
});

export const CIRCUIT_KEYS = Object.freeze(Object.keys(CIRCUIT_TEACHING));

export function circuitTeaching(key) {
  return CIRCUIT_TEACHING[key] ?? null;
}

export function circuitText(value, english = false) {
  return english ? value.en : value.ja;
}
