export type PathwayStepperPlane = "coronal" | "horizontal" | "sagittal";
export type BasalGangliaTarget = "caudate" | "putamen" | "pallidumExternal" | "pallidumInternal" | "subthalamic" | "substantiaNigra" | "thalamus";
export type BasalGangliaStep = {
  readonly key: string;
  readonly label: string;
  readonly targetKeys: readonly BasalGangliaTarget[];
  readonly plane: PathwayStepperPlane;
  readonly position: number;
  readonly quizRefs: readonly string[];
};
export type PapezStepKind = "section-label" | "schematic-3d" | "atlas-3d";
export type PapezStepSource = "existing-quiz-section-label" | "schematic-3d" | "atlas-3d";
export type PapezSectionTarget = "hippocampus" | "mammillaryBody" | "thalamus";
export type PapezSchematic3dTarget = "fornix";
export type PapezAtlas3dTarget = "cingulate" | "parahippocampal" | "entorhinal";
export type PapezStepTarget = PapezSectionTarget | PapezSchematic3dTarget | PapezAtlas3dTarget;
export type PapezStep = {
  readonly key: string;
  readonly label: string;
  readonly kind: PapezStepKind;
  readonly source: PapezStepSource;
  readonly targetKeys: readonly PapezStepTarget[];
  readonly plane?: PathwayStepperPlane;
  readonly position?: number;
  readonly quizRefs?: readonly string[];
  readonly labelIds?: readonly number[];
  readonly provenance: string;
  readonly note: string;
  readonly reviewStatus?: "project-reviewed-expert-pending";
};
export const BASAL_GANGLIA_STEPS: readonly BasalGangliaStep[];
export const BASAL_GANGLIA_TARGETS: readonly BasalGangliaTarget[];
export const BASAL_GANGLIA_LABEL_IDS: Readonly<Record<BasalGangliaTarget, readonly number[]>>;
export const BASAL_GANGLIA_TARGET_SET: ReadonlySet<string>;
export const PAPEZ_STEPS: readonly PapezStep[];
export const PAPEZ_SECTION_TARGETS: readonly PapezSectionTarget[];
export const PAPEZ_SCHEMATIC_3D_TARGETS: readonly PapezSchematic3dTarget[];
export const PAPEZ_ATLAS_3D_TARGETS: readonly PapezAtlas3dTarget[];
export const PAPEZ_STEP_KINDS: readonly PapezStepKind[];
export const PAPEZ_STEP_SOURCES: readonly PapezStepSource[];
export const PAPEZ_SECTION_LABEL_IDS: Readonly<Record<PapezSectionTarget, readonly number[]>>;
export const PAPEZ_TARGET_ALLOWLIST: Readonly<Record<PapezStepKind, readonly PapezStepTarget[]>>;
export function sliceIndexForPosition(plane: PathwayStepperPlane, position: number, dims: readonly number[]): number;
export function countLabelPixelsAtSlice(labels: Uint8Array, dims: readonly number[], plane: PathwayStepperPlane, position: number, labelIds: readonly number[]): number;
export function advanceBasalStepperIndex(current: number, stepCount?: number): number;
export function advancePapezStepperIndex(current: number, stepCount?: number): number;
export function startBasalGangliaStepperTimer(options?: {active?: boolean; onStep?: () => void; intervalMs?: number; schedule?: (callback: () => void, delay: number) => unknown; cancel?: (timer: unknown) => void}): () => void;
export function startPapezStepperTimer(options?: {active?: boolean; onStep?: () => void; intervalMs?: number; schedule?: (callback: () => void, delay: number) => unknown; cancel?: (timer: unknown) => void}): () => void;
export function auditBasalGangliaStepper(options?: {steps?: readonly BasalGangliaStep[]; quizQuestions?: readonly {target?: string; plane?: string; position?: number}[]; dims?: readonly number[]; labels?: Uint8Array; labelIdsByTarget?: Partial<Record<BasalGangliaTarget, readonly number[]>>}): {ok: boolean; errors: string[]; summary: Record<string, unknown>};
export function auditPapezStepper(options?: {steps?: readonly PapezStep[]; quizQuestions?: readonly {target?: string; plane?: string; position?: number}[]; dims?: readonly number[]; labels?: Uint8Array; labelIdsByTarget?: Partial<Record<PapezSectionTarget, readonly number[]>>}): {ok: boolean; errors: string[]; summary: Record<string, unknown>};
