type Text={ja:string;en:string};
export type SectionObservationGuide={observe:Text;compare:Text;reference:{title:string;url:string}};
const medial={title:"UTHealth — Medial structures",url:"https://nba.uth.tmc.edu/neuroanatomy/L1/Lab01p22_index.html"};
const limbic={title:"UTHealth — Limbic system: sectional review",url:"https://nba.uth.tmc.edu/neuroanatomy/L11/Lab11p09_index.html"};
const ventricles={title:"UTHealth — The ventricles",url:"https://nba.uth.tmc.edu/neuroanatomy/L4/Lab04p01_index.html"};
const visual={title:"UTHealth — Visual processing: cortical pathways",url:"https://nba.uth.tmc.edu/neuroscience/s2/chapter15.html"};
export const sectionObservationGuides:Partial<Record<string,SectionObservationGuide>>={
  aqueductPartial:{observe:{ja:"矢状断で第三脳室から第四脳室へ向かう細い腔を追い、水平断で中脳の正中にある位置を確かめます。",en:"Follow the narrow cavity from the third toward the fourth ventricle sagittally, then check its midline position in a horizontal midbrain section."},compare:{ja:"水道は腔です。周囲の組織や標本外の空間と分けて見ましょう。",en:"The aqueduct is a lumen: distinguish it from surrounding tissue and space outside the specimen."},reference:ventricles},
  anteriorCommissurePartial:{observe:{ja:"冠状断で正中を横切り、左右へ延びる白質束を探します。淡蒼球の下方を通る位置と、脳弓柱との前後関係が手がかりです。",en:"Look for the transverse white-matter bundle below the pallidum. Its relationship to the fornix columns helps locate it."},compare:{ja:"左右をつなぐ前交連と、前後に弯曲する脳弓を、連続断面で見分けます。",en:"Use adjacent sections to distinguish the transverse commissure from the curving fornix."},reference:limbic},
  septumPellucidumPartial:{observe:{ja:"左右の側脳室前角の間にある薄い隔壁を探します。脳梁の下方で、脳弓との位置関係も確かめます。",en:"Find the thin partition between the frontal horns, beneath the corpus callosum, and compare its position with the fornix."},compare:{ja:"透明中隔の薄い膜と、近くの白質束である脳梁・脳弓を区別します。",en:"Distinguish the thin septum from the nearby callosal and forniceal white-matter bundles."},reference:medial},
  fornixBodyPartial:{observe:{ja:"海馬側の海馬采から脚、正中近くの体部、下方へ向かう柱を順に探します。一枚で全体を見ようとせず、冠状断と矢状断を行き来しましょう。",en:"Look successively for the hippocampal fimbria, crura, body and descending columns, alternating coronal and sagittal sections."},compare:{ja:"海馬・脳梁・前交連を目印にします。一本の断面に離れて見えても、別々の構造とは限りません。",en:"Use hippocampus, corpus callosum and anterior commissure as landmarks. Separate profiles in one slice need not be separate structures."},reference:limbic},
  mammillaryBody:{observe:{ja:"漏斗の後方、視床下部の下面にある左右一対の小さな隆起を探します。冠状断では少し前後へ動かして、現れて消える範囲を確かめます。",en:"Find the paired small prominences behind the infundibulum on the inferior hypothalamic surface; follow their short extent through coronal sections."},compare:{ja:"乳頭体は灰白質の中継部で、そこへ向かう脳弓とは区別します。",en:"Distinguish this grey-matter relay from the fornix approaching it."},reference:limbic},
  opticChiasmPartial:{observe:{ja:"正中近くの視交叉と、その後方へ続く左右の視索を一緒に表示し、中央部から左右へ分かれる形を見ます。",en:"Display the central chiasm together with the paired optic tracts and compare their continuity and branching shape."},compare:{ja:"着色は位置の目安です。線維の交叉は形だけから判別せず、視覚路ガイドで確かめます。",en:"Colour locates the structures; fibre crossing is explained in the visual-pathway guide and is not resolved by this shape."},reference:visual},
  opticTractsPartial:{observe:{ja:"視交叉から後方へ延びる左右の帯を、外側膝状体と並べて観察します。断面を動かし、途中の位置関係を追います。",en:"Compare the paired bands behind the chiasm with the lateral geniculate bodies across adjacent slices."},compare:{ja:"視索と、外側膝状体から後頭葉へ向かう視放線は区別します。",en:"Distinguish the optic tract from the optic radiation leaving the geniculate relay."},reference:visual},
  lateralGeniculateBodies:{observe:{ja:"視床の後下外側にある左右の小さな核を探し、視索との位置関係を見ます。",en:"Find the small paired nuclei posteroinferolateral to the thalamus and compare their position with the optic tracts."},compare:{ja:"外側膝状体は視覚路の中継核です。視床全体や視索そのものとは分けて見ます。",en:"Identify the geniculate relay separately from the whole thalamus and optic tract."},reference:visual},
};
